import { NextResponse } from 'next/server'
import { services } from '@/lib/services'
import fs from 'fs'
import { cp } from 'fs/promises'
import path from 'path'
import os from 'os'
import { execSync } from 'child_process'

const BASE_PORT = 8642
const PORT_STEP = 10

// Template directories for baseline plugins and hooks
const TEMPLATE_PLUGINS = ['swarm_map_policy']
const TEMPLATE_HOOKS = ['lifecycle-notify']

/**
 * Install baseline plugins and hooks from infra/templates/ into an agent's data directory.
 * Gracefully skips if templates directory doesn't exist (e.g. running from upstream image).
 */
async function installBaselineTemplates(agentDataDir: string): Promise<void> {
  const templatesDir = path.join(process.cwd(), 'infra', 'templates')

  // Install plugins
  const pluginTemplatesDir = path.join(templatesDir, 'plugins')
  for (const pluginName of TEMPLATE_PLUGINS) {
    const srcDir = path.join(pluginTemplatesDir, pluginName)
    if (!fs.existsSync(srcDir)) continue
    const destDir = path.join(agentDataDir, 'plugins', pluginName)
    await cp(srcDir, destDir, { recursive: true })
  }

  // Install hooks
  const hookTemplatesDir = path.join(templatesDir, 'hooks')
  for (const hookName of TEMPLATE_HOOKS) {
    const srcDir = path.join(hookTemplatesDir, hookName)
    if (!fs.existsSync(srcDir)) continue
    const destDir = path.join(agentDataDir, 'hooks', hookName)
    await cp(srcDir, destDir, { recursive: true })
  }
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function expandPath(p: string): string {
  return p.replace(/^~/, os.homedir())
}

function nextAvailablePort(): number {
  const usedPorts = new Set<number>()

  // Query Docker directly for all ports in use
  try {
    const output = execSync(
      `docker ps --format '{{.Ports}}'`,
      { stdio: 'pipe', timeout: 5000 }
    ).toString()
    // Parse port mappings like "0.0.0.0:8642->8642/tcp"
    const portMatches = output.matchAll(/0\.0\.0\.0:(\d+)/g)
    for (const m of portMatches) {
      usedPorts.add(parseInt(m[1]))
    }
  } catch {}

  // Find next available in the hermes range (8642+, step 10)
  let port = BASE_PORT
  while (usedPorts.has(port)) {
    port += PORT_STEP
  }
  return port
}

function generateEnvContent(params: {
  name: string
  port: number
  provider: string
  primaryModel: string
  fallbackModel?: string
  llmKey?: string
  mattermostUrl?: string
  mattermostToken?: string
  telegramToken?: string
  signalPhone?: string
  githubToken?: string
  braveKey?: string
}): string {
  const { name, port, provider, llmKey, mattermostUrl, mattermostToken, telegramToken, signalPhone, githubToken, braveKey } = params

  const providerKeyMap: Record<string, string> = {
    anthropic: 'ANTHROPIC_API_KEY',
    openrouter: 'OPENROUTER_API_KEY',
    google: 'GOOGLE_API_KEY',
    bedrock: 'AWS_BEARER_TOKEN_BEDROCK',
  }

  const keyVar = providerKeyMap[provider]
  const keyLine = keyVar && llmKey ? `${keyVar}=${llmKey}` : keyVar ? `${keyVar}=` : '# No API key needed (local/ollama)'

  const lines = [
    `# Hermes Agent: ${name}`,
    `# Generated by hermes-swarm-map`,
    '',
    keyLine,
    `API_SERVER_PORT=${port}`,
    '',
    `# Platform integration`,
  ]

  if (mattermostUrl) {
    lines.push(`MATTERMOST_URL=${mattermostUrl}`)
  } else {
    lines.push(`# MATTERMOST_URL=`)
  }
  if (mattermostToken) {
    lines.push(`MATTERMOST_TOKEN=${mattermostToken}`)
  } else {
    lines.push(`# MATTERMOST_TOKEN=`)
  }
  if (mattermostUrl || mattermostToken) {
    lines.push(`MATTERMOST_ALLOWED_USERS=`)
    lines.push(`MATTERMOST_ALLOWED_CHANNELS=`)
  } else {
    lines.push(`# MATTERMOST_ALLOWED_USERS=`)
    lines.push(`# MATTERMOST_ALLOWED_CHANNELS=`)
  }
  if (telegramToken) {
    lines.push(`TELEGRAM_BOT_TOKEN=${telegramToken}`)
  } else {
    lines.push(`# TELEGRAM_BOT_TOKEN=`)
  }
  if (signalPhone) {
    lines.push(`SIGNAL_HTTP_URL=http://host.docker.internal:8080`)
    lines.push(`SIGNAL_ACCOUNT=${signalPhone}`)
    lines.push(`# SIGNAL_ALLOWED_USERS= (empty = no DMs; add phone numbers to allow, or * for all)`)
    lines.push(`# SIGNAL_GROUP_ALLOWED_USERS= (empty = no groups; add group IDs to allow, or * for all)`)
  } else {
    lines.push(`# SIGNAL_HTTP_URL=http://host.docker.internal:8080`)
    lines.push(`# SIGNAL_ACCOUNT=`)
  }

  // Swarm Map policy URL — allows agents to query their own harness config
  const hsmPort = process.env.PORT || '3002'
  lines.push('')
  lines.push(`# Swarm Map policy endpoint`)
  lines.push(`SWARM_MAP_POLICY_URL=http://host.docker.internal:${hsmPort}`)

  // Baseline agent identity & memory scoping
  lines.push('')
  lines.push(`# Agent identity & memory`)
  lines.push(`HERMES_MEMORY_SCOPE=channel`)
  lines.push(`HERMES_AGENT_NAME=${name}`)
  lines.push(`HERMES_HOME_CHANNEL=`)

  if (githubToken || braveKey) {
    lines.push('')
    lines.push('# Optional integrations')
    if (githubToken) lines.push(`GITHUB_TOKEN=${githubToken}`)
    if (braveKey) lines.push(`BRAVE_API_KEY=${braveKey}`)
  }

  return lines.join('\n') + '\n'
}

function generateConfigYaml(provider: string, primaryModel: string, fallbackModel?: string): string {
  const lines = [`model:`, `  provider: ${provider}`, `  default: ${primaryModel}`]
  if (fallbackModel) lines.push(`  fallback: ${fallbackModel}`)
  return lines.join('\n') + '\n'
}

function generateCompose(slug: string, port: number, agentDataDir: string, imageOrBuild: { image: string } | { build: string }): string {
  const sourceBlock = 'image' in imageOrBuild
    ? `    image: ${imageOrBuild.image}`
    : `    build:\n      context: ${imageOrBuild.build}\n      dockerfile: Dockerfile`

  return `# Generated by hermes-swarm-map — agent: ${slug}
services:
  hermes-${slug}:
${sourceBlock}
    container_name: hermes-${slug}
    restart: unless-stopped
    env_file:
      - ${agentDataDir}/.env
    ports:
      - published: ${port}
        target: 8642
      - published: 8095
        target: 8095   # Google OAuth callback (google-mcp auth flow)
    volumes:
      - ${agentDataDir}:/opt/data
      - ${path.join(os.homedir(), 'Documents/GitHub/google-mcp')}:/opt/google-mcp:ro
      - ${agentDataDir}/google-tokens:/opt/google/tokens
    command: gateway
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - SYS_CHROOT

networks:
  default:
    name: hermes-${slug}
`
}

export async function POST(request: Request) {
  try {
    const body = await request.json()
    const { name, provider, primaryModel, fallbackModel, persona, tier,
      mattermostEnabled, mattermostUrl, mattermostToken,
      telegramEnabled, telegramToken, signalEnabled, signalPhone,
      llmKey, githubToken, braveKey } = body

    if (!name || !provider || !primaryModel) {
      return NextResponse.json({ ok: false, error: 'name, provider, and primaryModel are required' }, { status: 400 })
    }

    const slug = slugify(name)
    if (!slug) {
      return NextResponse.json({ ok: false, error: 'Invalid name — could not slugify' }, { status: 400 })
    }

    // Check Docker is available
    if (!services.docker.isAvailable()) {
      return NextResponse.json({ ok: false, error: 'Docker is not available' }, { status: 500 })
    }

    // Load settings early — needed for image/build decision and directory resolution
    const settings = services.config.getSettings()

    // Determine whether to build from local source or use a pre-built image
    let imageOrBuild: { image: string } | { build: string }

    if (settings.useLocalBuild && settings.hermesDir) {
      const resolvedHermesDir = expandPath(settings.hermesDir)
      const dockerfilePath = path.join(resolvedHermesDir, 'Dockerfile')
      if (fs.existsSync(dockerfilePath)) {
        imageOrBuild = { build: resolvedHermesDir }
      } else {
        return NextResponse.json({ ok: false, error: `useLocalBuild enabled but no Dockerfile found at ${resolvedHermesDir}` }, { status: 400 })
      }
    } else {
      // Try pulling from Docker Hub first; if that fails (auth, network), check for local builds
      let hermesImage = settings.defaultImage || 'nousresearch/hermes-agent:latest'
      const pullResult = services.docker.pullImage(hermesImage)
      if (!pullResult.ok) {
        // Fallback: look for locally-built hermes images (from hermes-swarm build)
        // Prefer the most generic one (hermes-personal is the base build)
        try {
          const localOutput = execSync(
            'docker images --format "{{.Repository}}:{{.Tag}}" 2>/dev/null',
            { stdio: 'pipe', timeout: 5000 }
          ).toString()
          const hermesImages = localOutput.split('\n').filter(l => l.includes('hermes') && !l.includes('vertex') && !l.includes('litellm'))
          // Prefer images with "personal" (base build) or just any hermes image
          const preferred = hermesImages.find(i => i.includes('personal')) || hermesImages[0]
          if (preferred) {
            hermesImage = preferred.trim()
          } else {
            return NextResponse.json({ ok: false, error: `No Hermes image available. Pull failed: ${pullResult.error}` }, { status: 500 })
          }
        } catch {
          return NextResponse.json({ ok: false, error: `Image pull failed: ${pullResult.error}` }, { status: 500 })
        }
      }
      imageOrBuild = { image: hermesImage }
    }

    // Determine directories
    const swarmMapDataDir = settings.dataDir
      ? expandPath(settings.dataDir)
      : path.join(os.homedir(), '.hermes-swarm-map')
    const composeBaseDir = path.join(swarmMapDataDir, 'compose')

    const port = nextAvailablePort()

    const agentDataDir = path.join(os.homedir(), `.hermes-${slug}`)

    // Scaffold agent directory
    fs.mkdirSync(agentDataDir, { recursive: true })

    // Write .env
    const envContent = generateEnvContent({
      name: slug,
      port,
      provider,
      primaryModel,
      fallbackModel,
      llmKey,
      mattermostUrl: mattermostEnabled ? mattermostUrl : undefined,
      mattermostToken: mattermostEnabled ? mattermostToken : undefined,
      telegramToken: telegramEnabled ? telegramToken : undefined,
      signalPhone: signalEnabled ? signalPhone : undefined,
      githubToken,
      braveKey,
    })
    fs.writeFileSync(path.join(agentDataDir, '.env'), envContent, { mode: 0o600 })

    // Write config.yaml
    const configContent = generateConfigYaml(provider, primaryModel, fallbackModel)
    fs.writeFileSync(path.join(agentDataDir, 'config.yaml'), configContent, 'utf-8')

    // Write SOUL.md
    const soulContent = `# ${name}\n\n${persona || 'Describe this agent\'s purpose and personality here.'}\n`
    fs.writeFileSync(path.join(agentDataDir, 'SOUL.md'), soulContent, 'utf-8')

    // Create memories directory
    fs.mkdirSync(path.join(agentDataDir, 'memories'), { recursive: true })

    // Install baseline plugins and hooks from templates
    await installBaselineTemplates(agentDataDir)

    // Generate standalone compose
    const agentComposeDir = path.join(composeBaseDir, slug)
    fs.mkdirSync(agentComposeDir, { recursive: true })
    const composePath = path.join(agentComposeDir, 'docker-compose.yml')
    fs.writeFileSync(composePath, generateCompose(slug, port, agentDataDir, imageOrBuild), 'utf-8')

    // Start the container
    try {
      execSync(`docker compose -f ${composePath} up -d`, { stdio: 'pipe', timeout: 60000 })
    } catch (err) {
      return NextResponse.json({
        ok: false,
        error: `Failed to start container: ${err instanceof Error ? err.message : String(err)}`,
      }, { status: 500 })
    }

    // Health check
    const healthy = services.docker.healthCheck(`http://localhost:${port}/health`, 30000)

    // Register overlay via harness service
    const overlay = services.harness.createOverlay({
      name: slug,
      tier: tier ?? 'individual',
      platform: telegramEnabled ? 'telegram' : mattermostEnabled ? 'mattermost' : 'hermes',
      channel: `:${port}`,
      models: fallbackModel ? [primaryModel, fallbackModel] : [primaryModel],
    })

    return NextResponse.json({
      ok: true,
      harnessId: overlay.id,
      port,
      healthy,
    })
  } catch (err) {
    return NextResponse.json(
      { ok: false, error: err instanceof Error ? err.message : 'Unknown error' },
      { status: 500 }
    )
  }
}
