import { NextResponse } from 'next/server'
import { services } from '@/lib/services'
import fs from 'fs'
import path from 'path'
import os from 'os'
import { execSync } from 'child_process'

const BASE_PORT = 8642
const PORT_STEP = 10

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function expandPath(p: string): string {
  return p.replace(/^~/, os.homedir())
}

function nextAvailablePort(composeBaseDir: string): number {
  const usedPorts = new Set<number>()
  try {
    const entries = fs.readdirSync(composeBaseDir, { withFileTypes: true })
    for (const entry of entries) {
      if (!entry.isDirectory()) continue
      const composePath = path.join(composeBaseDir, entry.name, 'docker-compose.yml')
      try {
        const content = fs.readFileSync(composePath, 'utf-8')
        const portMatch = content.match(/published:\s*(\d+)/g)
        if (portMatch) {
          for (const m of portMatch) {
            const p = parseInt(m.replace('published:', '').trim(), 10)
            if (!isNaN(p)) usedPorts.add(p)
          }
        }
      } catch {}
    }
  } catch {}
  let port = BASE_PORT
  while (usedPorts.has(port)) {
    port += PORT_STEP
  }
  return port
}

function generateEnvContent(params: {
  name: string
  port: number
  provider: string
  primaryModel: string
  fallbackModel?: string
  llmKey?: string
  mattermostUrl?: string
  mattermostToken?: string
  telegramToken?: string
  githubToken?: string
  braveKey?: string
}): string {
  const { name, port, provider, llmKey, mattermostUrl, mattermostToken, telegramToken, githubToken, braveKey } = params

  const providerKeyMap: Record<string, string> = {
    anthropic: 'ANTHROPIC_API_KEY',
    openrouter: 'OPENROUTER_API_KEY',
    google: 'GOOGLE_API_KEY',
    bedrock: 'AWS_BEARER_TOKEN_BEDROCK',
  }

  const keyVar = providerKeyMap[provider]
  const keyLine = keyVar && llmKey ? `${keyVar}=${llmKey}` : keyVar ? `${keyVar}=` : '# No API key needed (local/ollama)'

  const lines = [
    `# Hermes Agent: ${name}`,
    `# Generated by hermes-swarm-map`,
    '',
    keyLine,
    `API_SERVER_PORT=${port}`,
    '',
    `# Platform integration`,
  ]

  if (mattermostUrl) {
    lines.push(`MATTERMOST_URL=${mattermostUrl}`)
  } else {
    lines.push(`# MATTERMOST_URL=`)
  }
  if (mattermostToken) {
    lines.push(`MATTERMOST_TOKEN=${mattermostToken}`)
  } else {
    lines.push(`# MATTERMOST_TOKEN=`)
  }
  if (telegramToken) {
    lines.push(`TELEGRAM_BOT_TOKEN=${telegramToken}`)
  } else {
    lines.push(`# TELEGRAM_BOT_TOKEN=`)
  }

  if (githubToken || braveKey) {
    lines.push('')
    lines.push('# Optional integrations')
    if (githubToken) lines.push(`GITHUB_TOKEN=${githubToken}`)
    if (braveKey) lines.push(`BRAVE_API_KEY=${braveKey}`)
  }

  return lines.join('\n') + '\n'
}

function generateConfigYaml(provider: string, primaryModel: string, fallbackModel?: string): string {
  const lines = [`model:`, `  provider: ${provider}`, `  default: ${primaryModel}`]
  if (fallbackModel) lines.push(`  fallback: ${fallbackModel}`)
  return lines.join('\n') + '\n'
}

function generateCompose(slug: string, port: number, agentDataDir: string): string {
  return `# Generated by hermes-swarm-map — agent: ${slug}
services:
  hermes-${slug}:
    image: nousresearch/hermes-agent:latest
    container_name: hermes-${slug}
    restart: unless-stopped
    env_file:
      - ${agentDataDir}/.env
    ports:
      - published: ${port}
        target: 8642
    volumes:
      - ${agentDataDir}:/root/.hermes

networks:
  default:
    name: hermes-${slug}
`
}

export async function POST(request: Request) {
  try {
    const body = await request.json()
    const { name, provider, primaryModel, fallbackModel, persona, tier,
      mattermostEnabled, mattermostUrl, mattermostToken,
      telegramEnabled, telegramToken, llmKey, githubToken, braveKey } = body

    if (!name || !provider || !primaryModel) {
      return NextResponse.json({ ok: false, error: 'name, provider, and primaryModel are required' }, { status: 400 })
    }

    const slug = slugify(name)
    if (!slug) {
      return NextResponse.json({ ok: false, error: 'Invalid name — could not slugify' }, { status: 400 })
    }

    // Check Docker is available
    if (!services.docker.isAvailable()) {
      return NextResponse.json({ ok: false, error: 'Docker is not available' }, { status: 500 })
    }

    // Pull the image
    const pullResult = services.docker.pullImage('nousresearch/hermes-agent:latest')
    if (!pullResult.ok) {
      return NextResponse.json({ ok: false, error: `Image pull failed: ${pullResult.error}` }, { status: 500 })
    }

    // Determine directories
    const settings = services.config.getSettings()
    const swarmMapDataDir = settings.dataDir
      ? expandPath(settings.dataDir)
      : path.join(os.homedir(), '.hermes-swarm-map')
    const composeBaseDir = path.join(swarmMapDataDir, 'compose')

    const port = nextAvailablePort(composeBaseDir)

    const agentDataDir = path.join(os.homedir(), `.hermes-${slug}`)

    // Scaffold agent directory
    fs.mkdirSync(agentDataDir, { recursive: true })

    // Write .env
    const envContent = generateEnvContent({
      name: slug,
      port,
      provider,
      primaryModel,
      fallbackModel,
      llmKey,
      mattermostUrl: mattermostEnabled ? mattermostUrl : undefined,
      mattermostToken: mattermostEnabled ? mattermostToken : undefined,
      telegramToken: telegramEnabled ? telegramToken : undefined,
      githubToken,
      braveKey,
    })
    fs.writeFileSync(path.join(agentDataDir, '.env'), envContent, { mode: 0o600 })

    // Write config.yaml
    const configContent = generateConfigYaml(provider, primaryModel, fallbackModel)
    fs.writeFileSync(path.join(agentDataDir, 'config.yaml'), configContent, 'utf-8')

    // Write SOUL.md
    const soulContent = `# ${name}\n\n${persona || 'Describe this agent\'s purpose and personality here.'}\n`
    fs.writeFileSync(path.join(agentDataDir, 'SOUL.md'), soulContent, 'utf-8')

    // Create memories directory
    fs.mkdirSync(path.join(agentDataDir, 'memories'), { recursive: true })

    // Generate standalone compose
    const agentComposeDir = path.join(composeBaseDir, slug)
    fs.mkdirSync(agentComposeDir, { recursive: true })
    const composePath = path.join(agentComposeDir, 'docker-compose.yml')
    fs.writeFileSync(composePath, generateCompose(slug, port, agentDataDir), 'utf-8')

    // Start the container
    try {
      execSync(`docker compose -f ${composePath} up -d`, { stdio: 'pipe', timeout: 60000 })
    } catch (err) {
      return NextResponse.json({
        ok: false,
        error: `Failed to start container: ${err instanceof Error ? err.message : String(err)}`,
      }, { status: 500 })
    }

    // Health check
    const healthy = services.docker.healthCheck(`http://localhost:${port}/health`, 30000)

    // Register overlay via harness service
    const overlay = services.harness.createOverlay({
      name: slug,
      tier: tier ?? 'individual',
      platform: telegramEnabled ? 'telegram' : mattermostEnabled ? 'mattermost' : 'hermes',
      channel: `:${port}`,
      models: fallbackModel ? [primaryModel, fallbackModel] : [primaryModel],
    })

    return NextResponse.json({
      ok: true,
      harnessId: overlay.id,
      port,
      healthy,
    })
  } catch (err) {
    return NextResponse.json(
      { ok: false, error: err instanceof Error ? err.message : 'Unknown error' },
      { status: 500 }
    )
  }
}
