import { describe, it, expect } from 'vitest'
import {
  addStateMigrationToCompose,
  isDeployBornCompose,
  setComposeImage,
  generateStandaloneCompose,
} from '@/lib/services/harness-compose'
import { generateAgentCompose } from '@/lib/services/agent-deploy-templates'

// Pre-PR2 fixtures: what real compose files on the Mini look like TODAY
// (generated before the init-service era). The transform must migrate these
// without regenerating them.

const PRE_PR2_PLAIN = `# Generated by hermes-swarm-map — agent: sci
services:
  hermes-sci:
    image: ghcr.io/nimblecoorg/hermes-agent-mt:latest
    container_name: hermes-sci
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - /home/u/.hermes-sci/.env
    environment:
      - HOME=/opt/data
      - HERMES_HOME=/opt/data
    ports:
      - published: 8642
        target: 8642
    volumes:
      - /home/u/.hermes-sci:/opt/data
    command: gateway
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'

networks:
  default:
    name: hermes-sci
`

const PRE_PR2_VPN = `# Generated by hermes-swarm-map — agent: sci (VPN mode)
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-sci
    restart: unless-stopped
    volumes:
      - /home/u/.hermes-sci/wg-config:/config

  camofox:
    image: ghcr.io/jo-inc/camofox-browser:1.13.0
    container_name: camofox-sci
    restart: unless-stopped
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    volumes:
      - /home/u/.hermes-sci/.camofox:/data

  hermes-sci:
    image: ghcr.io/nimblecoorg/hermes-agent-mt:latest
    container_name: hermes-sci
    restart: unless-stopped
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    env_file:
      - /home/u/.hermes-sci/.env
    volumes:
      - /home/u/.hermes-sci:/opt/data
    command: gateway

networks:
  default:
    name: hermes-sci
`

const PRE_PR2_DEPLOY = `# Generated by hermes-swarm-map — agent: sci
services:
  hermes-sci:
    image: ghcr.io/nimblecoorg/hermes-agent-mt:latest
    container_name: hermes-sci
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - /home/u/.hermes-sci/.env
    ports:
      - published: 8642
        target: 8642
      - published: 9095
        target: 8095   # Google OAuth callback (google-multiplayer-mcp auth flow)
    volumes:
      - /home/u/.hermes-sci:/opt/data
      - /opt/gmcp:/opt/google-multiplayer-mcp:ro
      - /home/u/.hermes-sci/google-tokens:/opt/google/tokens
    command: gateway
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:false
    read_only: true
    tmpfs:
      - /tmp
      - /run:exec

networks:
  default:
    name: hermes-sci
`

describe('addStateMigrationToCompose', () => {
  it('migrates a pre-PR2 plain compose: init service, volume, gate, trailer', () => {
    const out = addStateMigrationToCompose(PRE_PR2_PLAIN, 'sci', '/home/u/.hermes-sci')
    expect(out).toContain('  state-init-sci:')
    expect(out).toContain('container_name: state-init-sci')
    // reuses the hermes source block
    expect(out.split('image: ghcr.io/nimblecoorg/hermes-agent-mt:latest').length).toBe(3)
    // gate on the hermes service (it had no depends_on before)
    expect(out).toMatch(/state-init-sci:\s*\n\s*condition: service_completed_successfully/)
    // /state mount added to hermes, data-dir mount untouched
    expect(out).toContain('      - /home/u/.hermes-sci:/opt/data\n      - hermes-state-sci:/state')
    // top-level trailer with pinned name
    expect(out).toMatch(/^volumes:\n  hermes-state-sci:\n    name: hermes-state-sci$/m)
  })

  it('converts VPN list-form depends_on to map form and keeps sidecars intact', () => {
    const out = addStateMigrationToCompose(PRE_PR2_VPN, 'sci', '/home/u/.hermes-sci')
    const hermesBlock = out.slice(out.indexOf('  hermes-sci:'))
    expect(hermesBlock).toMatch(/depends_on:\s*\n\s*wireguard:\s*\n\s*condition: service_started/)
    expect(hermesBlock).toMatch(/state-init-sci:\s*\n\s*condition: service_completed_successfully/)
    expect(hermesBlock).not.toMatch(/depends_on:\s*\n\s*- wireguard/)
    // untouched: wireguard + camofox services (incl. camofox's own list-form dep)
    expect(out).toContain('image: lscr.io/linuxserver/wireguard:latest')
    expect(out).toMatch(/camofox-sci[\s\S]*?depends_on:\s*\n\s*- wireguard/)
    expect(out).toContain('network_mode: "service:wireguard"')
  })

  it('preserves deploy-born hardening (read_only/tmpfs/google mounts) verbatim', () => {
    const out = addStateMigrationToCompose(PRE_PR2_DEPLOY, 'sci', '/home/u/.hermes-sci')
    expect(out).toContain('read_only: true')
    expect(out).toContain('- /run:exec')
    expect(out).toContain('/opt/gmcp:/opt/google-multiplayer-mcp:ro')
    expect(out).toContain('/opt/google/tokens')
    expect(out).toContain('  state-init-sci:')
    // /state added AFTER the google mounts (appended to the volumes list)
    expect(out).toContain('      - hermes-state-sci:/state')
  })

  it('is idempotent: already-migrated compose (incl. freshly generated) returns unchanged', () => {
    const migrated = addStateMigrationToCompose(PRE_PR2_PLAIN, 'sci', '/home/u/.hermes-sci')
    expect(addStateMigrationToCompose(migrated, 'sci', '/home/u/.hermes-sci')).toBe(migrated)

    const freshPlain = generateStandaloneCompose('sci', 8642, '/home/u/.hermes-sci', {})
    expect(addStateMigrationToCompose(freshPlain, 'sci', '/home/u/.hermes-sci')).toBe(freshPlain)
    const freshDeploy = generateAgentCompose('sci', 8642, '/home/u/.hermes-sci', { image: 'ghcr.io/x:1' })
    expect(addStateMigrationToCompose(freshDeploy, 'sci', '/home/u/.hermes-sci')).toBe(freshDeploy)
  })

  it('REFUSES (throws) when anchors are missing — never falls through', () => {
    expect(() => addStateMigrationToCompose('services:\n  other:\n    image: x\n', 'sci', '/d'))
      .toThrow(/no "hermes-sci:" service/)
    const noVolumes = PRE_PR2_PLAIN.replace(/ {4}volumes:\n {6}- \/home\/u\/\.hermes-sci:\/opt\/data\n/, '')
    expect(() => addStateMigrationToCompose(noVolumes, 'sci', '/home/u/.hermes-sci'))
      .toThrow(/no volumes: key/)
    const withTopVolumes = PRE_PR2_PLAIN + '\nvolumes:\n  other-vol:\n'
    expect(() => addStateMigrationToCompose(withTopVolumes, 'sci', '/home/u/.hermes-sci'))
      .toThrow(/top-level volumes/)
  })

  it('handles a build:-sourced hermes service and stays setComposeImage-compatible', () => {
    const buildCompose = PRE_PR2_PLAIN.replace(
      '    image: ghcr.io/nimblecoorg/hermes-agent-mt:latest',
      '    build:\n      context: /src/hermes-agent-mt\n      dockerfile: Dockerfile',
    )
    const out = addStateMigrationToCompose(buildCompose, 'sci', '/home/u/.hermes-sci')
    expect(out.split('context: /src/hermes-agent-mt').length).toBe(3) // hermes + init
    // CD image pin still works on the transformed file and updates BOTH blocks
    const pinned = setComposeImage(out, 'ghcr.io/pinned:2')
    expect(pinned).not.toContain('build:')
    expect(pinned.split('image: ghcr.io/pinned:2').length).toBe(3)
  })
})

describe('isDeployBornCompose', () => {
  it('detects deploy-born markers and not standalone composes', () => {
    expect(isDeployBornCompose(PRE_PR2_DEPLOY)).toBe(true)
    expect(isDeployBornCompose(PRE_PR2_PLAIN)).toBe(false)
    expect(isDeployBornCompose(PRE_PR2_VPN)).toBe(false)
    // fresh generator outputs classify the same way
    expect(isDeployBornCompose(generateAgentCompose('x', 8642, '/d', { image: 'i' }))).toBe(true)
    expect(isDeployBornCompose(generateStandaloneCompose('x', 8642, '/d', {}))).toBe(false)
  })
})
