import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import fs from 'fs'
import os from 'os'
import path from 'path'

// The migration reads settings (dataDir, defaultImage) and writes the
// normalized defaultImage back through the same service.
const getSettings = vi.fn()
const updateSettings = vi.fn()
vi.mock('@/lib/services', () => ({
  services: { config: { getSettings: (...a: unknown[]) => getSettings(...a), updateSettings: (...a: unknown[]) => updateSettings(...a) } },
}))

import { normalizeImageRef, migrateLegacyImageRefs } from '@/lib/services/image-migration'

const LEGACY = 'ghcr.io/nimblecoai/hermes-agent-mt'
const CURRENT = 'ghcr.io/nimblecoorg/hermes-agent-mt'

describe('normalizeImageRef', () => {
  it('migrates the bare legacy repo path', () => {
    expect(normalizeImageRef(LEGACY)).toBe(CURRENT)
  })

  it('preserves tags', () => {
    expect(normalizeImageRef(`${LEGACY}:latest`)).toBe(`${CURRENT}:latest`)
    expect(normalizeImageRef(`${LEGACY}:2026-07-21`)).toBe(`${CURRENT}:2026-07-21`)
  })

  it('preserves digests', () => {
    expect(normalizeImageRef(`${LEGACY}@sha256:abc123`)).toBe(`${CURRENT}@sha256:abc123`)
  })

  it('leaves current refs alone', () => {
    expect(normalizeImageRef(`${CURRENT}:latest`)).toBe(`${CURRENT}:latest`)
  })

  it('does not match prefixes of longer repo names or substrings', () => {
    expect(normalizeImageRef(`${LEGACY}-fork:latest`)).toBe(`${LEGACY}-fork:latest`)
    expect(normalizeImageRef(`example.com/${LEGACY}:latest`)).toBe(`example.com/${LEGACY}:latest`)
  })

  it('leaves unrelated images alone', () => {
    expect(normalizeImageRef('ollama/ollama')).toBe('ollama/ollama')
    expect(normalizeImageRef('ghcr.io/jo-inc/camofox-browser:1.13.0')).toBe('ghcr.io/jo-inc/camofox-browser:1.13.0')
  })
})

// Minimal but realistic generated compose — matches the shape
// readComposeImage/setComposeImage parse (4-space image line under the
// 2-space hermes-<name> service key).
function composeFixture(agent: string, image: string): string {
  return `# Generated by hermes-swarm-map — agent: ${agent}
services:
  hermes-${agent}:
    image: ${image}
    container_name: hermes-${agent}
    restart: unless-stopped
    env_file:
      - /home/u/.hermes-${agent}/.env
`
}

describe('migrateLegacyImageRefs', () => {
  let tmp: string

  beforeEach(() => {
    tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'img-migration-'))
    getSettings.mockReset()
    updateSettings.mockReset()
  })

  afterEach(() => {
    fs.rmSync(tmp, { recursive: true, force: true })
  })

  function writeCompose(agent: string, image: string): string {
    const dir = path.join(tmp, 'compose', agent)
    fs.mkdirSync(dir, { recursive: true })
    const p = path.join(dir, 'docker-compose.yml')
    fs.writeFileSync(p, composeFixture(agent, image), 'utf-8')
    return p
  }

  it('rewrites legacy defaultImage in settings and legacy compose files', () => {
    getSettings.mockReturnValue({ dataDir: tmp, defaultImage: `${LEGACY}:latest` })
    const legacyPath = writeCompose('chur-bot', `${LEGACY}:latest`)
    const currentPath = writeCompose('pmf', `${CURRENT}:latest`)

    const result = migrateLegacyImageRefs()

    expect(updateSettings).toHaveBeenCalledWith({ defaultImage: `${CURRENT}:latest` })
    expect(result.settingsChanged).toBe(true)
    expect(result.composeMigrated).toEqual([legacyPath])
    expect(result.composeFailed).toEqual([])
    expect(fs.readFileSync(legacyPath, 'utf-8')).toContain(`image: ${CURRENT}:latest`)
    expect(fs.readFileSync(legacyPath, 'utf-8')).not.toContain('nimblecoai')
    // untouched file stays byte-identical
    expect(fs.readFileSync(currentPath, 'utf-8')).toBe(composeFixture('pmf', `${CURRENT}:latest`))
  })

  it('is idempotent', () => {
    getSettings.mockReturnValue({ dataDir: tmp, defaultImage: `${CURRENT}:latest` })
    const p = writeCompose('chur-bot', `${LEGACY}:latest`)

    const first = migrateLegacyImageRefs()
    expect(first.composeMigrated).toEqual([p])

    const second = migrateLegacyImageRefs()
    expect(second.settingsChanged).toBe(false)
    expect(second.composeMigrated).toEqual([])
    expect(updateSettings).not.toHaveBeenCalled()
  })

  it('skips local-build composes and survives a missing compose dir', () => {
    getSettings.mockReturnValue({ dataDir: tmp })
    const dir = path.join(tmp, 'compose', 'dev-agent')
    fs.mkdirSync(dir, { recursive: true })
    fs.writeFileSync(
      path.join(dir, 'docker-compose.yml'),
      `services:\n  hermes-dev-agent:\n    build:\n      context: /home/u/hermes-agent-mt\n`,
      'utf-8',
    )
    expect(migrateLegacyImageRefs().composeMigrated).toEqual([])

    fs.rmSync(path.join(tmp, 'compose'), { recursive: true, force: true })
    expect(() => migrateLegacyImageRefs()).not.toThrow()
  })

  it('never throws when settings access fails', () => {
    getSettings.mockImplementation(() => { throw new Error('boom') })
    expect(() => migrateLegacyImageRefs()).not.toThrow()
  })
})
