/**
 * Pure templating for the create-new deploy flow: the agent `.env` body and the
 * standalone docker-compose. Extracted from app/api/setup/deploy/route.ts so the
 * templating is unit-testable and the route stays orchestration-only.
 */
import { hsmBaseUrl } from './hsm-url'
import { anthropicEnvVarForValue } from './keys'
import { ollamaSidecar } from './harness-compose'

export function generateEnvContent(params: {
  name: string
  port: number
  provider: string
  primaryModel: string
  fallbackModel?: string
  llmKey?: string
  bundledOllama?: boolean
  mattermostUrl?: string
  mattermostToken?: string
  telegramToken?: string
  discordToken?: string
  slackBotToken?: string
  slackAppToken?: string
  signalPhone?: string
  githubToken?: string
  braveKey?: string
  browserEnabled?: boolean
}): string {
  const { name, port, provider, llmKey, bundledOllama, mattermostUrl, mattermostToken, telegramToken, discordToken, slackBotToken, slackAppToken, signalPhone, githubToken, braveKey, browserEnabled } = params

  const providerKeyMap: Record<string, string> = {
    anthropic: 'ANTHROPIC_API_KEY',
    openrouter: 'OPENROUTER_API_KEY',
    google: 'GOOGLE_API_KEY',
    bedrock: 'AWS_BEARER_TOKEN_BEDROCK',
    zai: 'GLM_API_KEY',
  }

  // Anthropic credentials route to ANTHROPIC_API_KEY or ANTHROPIC_TOKEN by value
  // shape (see anthropicEnvVarForValue) — a bearer token in ANTHROPIC_API_KEY
  // produces a conflicting dual-header request the API rejects.
  const keyVar = provider === 'anthropic' && llmKey
    ? anthropicEnvVarForValue(llmKey)
    : providerKeyMap[provider]
  const keyLine = keyVar && llmKey ? `${keyVar}=${llmKey}` : keyVar ? `${keyVar}=` : '# No API key needed (local/ollama)'

  // Host-GPU ollama (default) points at the host daemon; bundled mode points at
  // the in-compose `ollama-<name>` sidecar (see generateAgentCompose).
  const ollamaLine = (provider === 'ollama' || provider === 'custom')
    ? (bundledOllama
        ? `OLLAMA_BASE_URL=http://ollama-${name}:11434/v1`
        : `OLLAMA_BASE_URL=http://host.docker.internal:11434/v1`)
    : null

  const lines = [
    `# Hermes Agent: ${name}`,
    `# Generated by hermes-swarm-map`,
    '',
    keyLine,
    `API_SERVER_PORT=${port}`,
    '',
    `# Platform integration`,
  ]
  if (ollamaLine) lines.push(ollamaLine)

  if (mattermostUrl) {
    lines.push(`MATTERMOST_URL=${mattermostUrl}`)
  } else {
    lines.push(`# MATTERMOST_URL=`)
  }
  if (mattermostToken) {
    lines.push(`MATTERMOST_TOKEN=${mattermostToken}`)
  } else {
    lines.push(`# MATTERMOST_TOKEN=`)
  }
  if (mattermostUrl || mattermostToken) {
    lines.push(`MATTERMOST_ALLOWED_USERS=`)
    lines.push(`MATTERMOST_ALLOWED_CHANNELS=`)
  } else {
    lines.push(`# MATTERMOST_ALLOWED_USERS=`)
    lines.push(`# MATTERMOST_ALLOWED_CHANNELS=`)
  }
  if (telegramToken) {
    lines.push(`TELEGRAM_BOT_TOKEN=${telegramToken}`)
  } else {
    lines.push(`# TELEGRAM_BOT_TOKEN=`)
  }
  if (discordToken) {
    lines.push(`DISCORD_BOT_TOKEN=${discordToken}`)
    lines.push(`DISCORD_ALLOWED_USERS=`)
    lines.push(`DISCORD_ALLOWED_CHANNELS=`)
    lines.push(`DISCORD_REQUIRE_MENTION=true`)
  } else {
    lines.push(`# DISCORD_BOT_TOKEN=`)
    lines.push(`# DISCORD_ALLOWED_USERS=`)
    lines.push(`# DISCORD_ALLOWED_CHANNELS=`)
  }
  if (slackBotToken && slackAppToken) {
    lines.push(`SLACK_BOT_TOKEN=${slackBotToken}`)
    lines.push(`SLACK_APP_TOKEN=${slackAppToken}`)
    lines.push(`SLACK_ALLOWED_USERS=`)
    lines.push(`SLACK_ALLOWED_CHANNELS=`)
    lines.push(`SLACK_REQUIRE_MENTION=true`)
  } else {
    lines.push(`# SLACK_BOT_TOKEN=`)
    lines.push(`# SLACK_APP_TOKEN=`)
    lines.push(`# SLACK_ALLOWED_USERS=`)
    lines.push(`# SLACK_ALLOWED_CHANNELS=`)
  }
  if (signalPhone) {
    lines.push(`SIGNAL_HTTP_URL=http://host.docker.internal:8080`)
    lines.push(`SIGNAL_ACCOUNT=${signalPhone}`)
    lines.push(`# SIGNAL_ALLOWED_USERS= (empty = no DMs; add phone numbers to allow, or * for all)`)
    lines.push(`# SIGNAL_GROUP_ALLOWED_USERS= (empty = no groups; add group IDs to allow, or * for all)`)
  } else {
    lines.push(`# SIGNAL_HTTP_URL=http://host.docker.internal:8080`)
    lines.push(`# SIGNAL_ACCOUNT=`)
  }

  // Web extraction (self-hosted Firecrawl — no API key needed)
  lines.push('')
  lines.push(`# Web extraction (self-hosted Firecrawl)`)
  lines.push(`FIRECRAWL_API_URL=http://host.docker.internal:3002`)

  // Swarm Map policy URL — allows agents to query their own harness config
  const hsmUrl = hsmBaseUrl()
  lines.push('')
  lines.push(`# HSM policy endpoint`)
  lines.push(`HSM_URL=${hsmUrl}`)
  lines.push(`SWARM_MAP_POLICY_URL=${hsmUrl}`)

  // Baseline agent identity & memory scoping
  lines.push('')
  lines.push(`# Agent identity & memory`)
  lines.push(`HOME=/opt/data`)
  lines.push(`HERMES_MEMORY_SCOPE=channel`)
  lines.push(`HERMES_AGENT_NAME=${name}`)
  lines.push(`HERMES_HOME_CHANNEL=`)

  // Policy defaults (secure by default)
  lines.push('')
  lines.push(`# Policy defaults (secure by default)`)
  lines.push(`HERMES_DM_POLICY=approved-only`)
  lines.push(`HERMES_APPROVAL_ADMIN_ONLY=true`)
  lines.push(`SIGNAL_REQUIRE_MENTION=true`)
  lines.push(`TELEGRAM_REQUIRE_MENTION=true`)
  lines.push(`MATTERMOST_REQUIRE_MENTION=true`)
  lines.push(`SIGNAL_OBSERVE_UNMENTIONED=true`)
  lines.push(`MATTERMOST_OBSERVE_UNMENTIONED=true`)
  lines.push(`TELEGRAM_OBSERVE_UNMENTIONED_GROUP_MESSAGES=true`)
  lines.push(`SIGNAL_GROUP_INVITE_POLICY=approved-only`)
  // Browser tools (Camofox)
  if (browserEnabled) {
    lines.push('')
    lines.push('# Browser tools (Camofox)')
    lines.push('CAMOFOX_URL=http://host.docker.internal:9377')
  }
  if (githubToken || braveKey) {
    lines.push('')
    lines.push('# Optional integrations')
    if (githubToken) lines.push(`GITHUB_TOKEN=${githubToken}`)
    if (braveKey) lines.push(`BRAVE_API_KEY=${braveKey}`)
  }

  return lines.join('\n') + '\n'
}

export function generateAgentCompose(
  slug: string,
  port: number,
  agentDataDir: string,
  imageOrBuild: { image: string } | { build: string },
  options?: {
    googleMcpDir?: string
    githubMcpEnabled?: boolean
    bundledOllama?: boolean
    ollamaImage?: string
    memory?: string
    cpus?: string
  },
): string {
  const { googleMcpDir, githubMcpEnabled, bundledOllama, ollamaImage, memory, cpus } = options ?? {}
  const sourceBlock = 'image' in imageOrBuild
    ? `    image: ${imageOrBuild.image}`
    : `    build:\n      context: ${imageOrBuild.build}\n      dockerfile: Dockerfile`

  // Google OAuth callback port — offset from agent's main port to avoid conflicts
  // e.g. agent on 8642 → OAuth on 9095, agent on 8652 → OAuth on 9105
  const oauthPort = port + 453  // 8642 + 453 = 9095 (avoids collisions with agent port range)
  const googleMcpPorts = googleMcpDir
    ? `      - published: ${oauthPort}\n        target: 8095   # Google OAuth callback (google-multiplayer-mcp auth flow)\n`
    : ``

  const googleMcpVolumes = googleMcpDir
    ? `      - ${googleMcpDir}:/opt/google-multiplayer-mcp:ro\n      - ${agentDataDir}/google-tokens:/opt/google/tokens\n`
    : ``

  const githubEnv = githubMcpEnabled
    ? `    environment:\n      - GITHUB_PERSONAL_ACCESS_TOKEN=\${GITHUB_TOKEN}\n`
    : ''

  // Optional bundled ollama sidecar (CPU, tiny model) — shares the default named
  // network, so hermes reaches it at http://ollama-<slug>:11434 (matches the env
  // OLLAMA_BASE_URL written in bundled mode). Reuses the same sidecar definition
  // as the standalone generator (harness-compose.ts) — single source of truth.
  const ollamaBlock = bundledOllama ? ollamaSidecar(slug, agentDataDir, ollamaImage, '') : ''
  const ollamaDepends = bundledOllama
    ? `    depends_on:\n      ollama-${slug}:\n        condition: service_healthy\n`
    : ''

  return `# Generated by hermes-swarm-map — agent: ${slug}
services:
${ollamaBlock}  hermes-${slug}:
${sourceBlock}
    container_name: hermes-${slug}
    restart: unless-stopped
${ollamaDepends}    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ${agentDataDir}/.env
${githubEnv}    ports:
      - published: ${port}
        target: 8642
${googleMcpPorts}    volumes:
      - ${agentDataDir}:/opt/data
${googleMcpVolumes}    command: gateway
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:false
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
      # s6-overlay execs its init from /run; a bare tmpfs is mounted noexec,
      # which makes the agent restart-loop at boot (exit 126). Mount it exec.
      - /run:exec
    deploy:
      resources:
        limits:
          memory: ${memory ?? '2G'}
          cpus: '${cpus ?? '2.0'}'

networks:
  default:
    name: hermes-${slug}
`
}
