import { describe, it, expect, vi, afterEach } from 'vitest'
import os from 'os'
import {
  expandHostPath,
  generateStandaloneCompose,
  renderExtraEnv,
  renderExtraMounts,
  validateExtraEnv,
  validateExtraMounts,
} from './harness-compose'
import type { ExtraMount } from '@/lib/types'

/**
 * The lines of a service's block-scalar list, e.g. `volumes:` or
 * `environment:`, without parsing YAML (the project has no yaml dependency and
 * this is not worth adding one for). Walks from the key to the first line that
 * dedents out of the list, so an entry emitted at the wrong indent — which
 * would land in the wrong block or break the file — fails the assertion.
 */
function listEntries(compose: string, service: string, key: string): string[] {
  const lines = compose.split('\n')
  const serviceIdx = lines.findIndex((l) => l === `  ${service}:`)
  if (serviceIdx < 0) throw new Error(`no service ${service}`)
  let keyIdx = -1
  for (let i = serviceIdx + 1; i < lines.length; i++) {
    if (/^ {2}\S/.test(lines[i])) break // next service
    if (lines[i] === `    ${key}:`) { keyIdx = i; break }
  }
  if (keyIdx < 0) throw new Error(`no ${key}: in ${service}`)
  const out: string[] = []
  for (let i = keyIdx + 1; i < lines.length; i++) {
    const line = lines[i]
    if (/^ {6}#/.test(line)) continue // comment inside the list
    if (!/^ {6}- /.test(line)) break
    out.push(line.slice(8))
  }
  return out
}

// The bug these exist for: an agent needed a host path, someone added the
// mount by hand under the "# Generated by hermes-swarm-map" header, and the
// next regeneration silently dropped it. The container came back healthy with
// the capability gone. So: mounts are config, config survives regeneration,
// and a malformed mount fails generation loudly instead of rendering into
// something that means more than it says.

const agentName = 'test-agent'
const port = 8642
const dataDir = '/opt/hermes/test-agent'

const SPOOL: ExtraMount = {
  hostPath: '/Users/juni/.iris/nimbleco/intake',
  containerPath: '/opt/iris-intake',
  mode: 'rw',
  note: 'approval-gate spool: the only writable gate path',
}
const PACKAGE: ExtraMount = {
  hostPath: '/Users/juni/iris-gates/nimbleco',
  containerPath: '/opt/iris',
}

describe('renderExtraMounts', () => {
  it('renders nothing when there are no mounts', () => {
    expect(renderExtraMounts()).toBe('')
    expect(renderExtraMounts([])).toBe('')
  })

  it('defaults mode to ro — write access has to be asked for', () => {
    expect(renderExtraMounts([PACKAGE])).toBe(
      '      - /Users/juni/iris-gates/nimbleco:/opt/iris:ro\n')
  })

  it('renders the note as a comment above the mount', () => {
    const out = renderExtraMounts([SPOOL])
    expect(out).toContain('# approval-gate spool: the only writable gate path')
    expect(out).toContain('- /Users/juni/.iris/nimbleco/intake:/opt/iris-intake:rw')
  })

  // --- injection: every value lands in generated YAML -----------------------

  it('refuses a newline in a path — it could append arbitrary compose keys', () => {
    for (const evil of [
      { hostPath: '/a\n    privileged: true', containerPath: '/b' },
      { hostPath: '/a', containerPath: '/b\n      - /etc:/etc:rw' },
    ] as ExtraMount[]) {
      expect(() => renderExtraMounts([evil])).toThrow(/newline/)
    }
  })

  it('refuses a colon in a path — it could forge the mount mode', () => {
    // '/host:/container:rw' smuggled through what looks like one path would
    // turn a declared-ro mount into a writable one.
    expect(() => renderExtraMounts([
      { hostPath: '/etc:/etc:rw', containerPath: '/b', mode: 'ro' },
    ])).toThrow(/forge the mount mode/)
  })

  it('refuses a relative path', () => {
    expect(() => renderExtraMounts([
      { hostPath: 'relative/path', containerPath: '/b' },
    ])).toThrow(/absolute/)
  })

  // --- tilde expansion ------------------------------------------------------
  //
  // `~/.iris/...` is the spelling harness.ts's expandPath accepts everywhere
  // else, so it is what someone hand-editing harnesses.json will type. It is
  // ALSO non-absolute, so before expansion it hit the absolute-path throw — and
  // that throw ran mid-PUT, after the .env had already been written. Compose
  // itself does not expand `~`, so the expansion has to happen here and the
  // EXPANDED path is what must be rendered.

  describe('tilde expansion', () => {
    afterEach(() => vi.restoreAllMocks())

    it('expands a leading ~ in a host path to the real home directory', () => {
      vi.spyOn(os, 'homedir').mockReturnValue('/Users/juni')
      expect(renderExtraMounts([
        { hostPath: '~/.iris/nimbleco/intake', containerPath: '/opt/iris-intake', mode: 'rw' },
      ])).toBe('      - /Users/juni/.iris/nimbleco/intake:/opt/iris-intake:rw\n')
      expect(validateExtraMounts([
        { hostPath: '~/.iris/nimbleco/intake', containerPath: '/opt/iris-intake' },
      ])).toBeNull()
    })

    it('expands a bare ~', () => {
      vi.spyOn(os, 'homedir').mockReturnValue('/Users/juni')
      expect(expandHostPath('~')).toBe('/Users/juni')
    })

    it('does NOT expand ~user — that would silently invent a wrong path', () => {
      vi.spyOn(os, 'homedir').mockReturnValue('/Users/juni')
      // /Users/junisomeone/x would be absolute, pass validation, and bind-mount
      // a directory nobody named. Better to fail the absolute check.
      expect(expandHostPath('~someone/x')).toBe('~someone/x')
      expect(() => renderExtraMounts([
        { hostPath: '~someone/x', containerPath: '/b' },
      ])).toThrow(/absolute/)
    })

    it('leaves container paths alone — the home dir here is the HOST\'s', () => {
      vi.spyOn(os, 'homedir').mockReturnValue('/Users/juni')
      expect(() => renderExtraMounts([
        { hostPath: '/a', containerPath: '~/b' },
      ])).toThrow(/absolute/)
    })
  })

  it('refuses an empty path', () => {
    expect(() => renderExtraMounts([
      { hostPath: '', containerPath: '/b' },
    ])).toThrow(/required/)
  })

  it('refuses a mode that is not ro or rw', () => {
    expect(() => renderExtraMounts([
      { hostPath: '/a', containerPath: '/b', mode: 'z' as 'ro' },
    ])).toThrow(/must be 'ro' or 'rw'/)
  })

  it('names the offending index so a bad entry is findable', () => {
    expect(() => renderExtraMounts([PACKAGE, { hostPath: 'nope', containerPath: '/b' }]))
      .toThrow(/extraMounts\[1\]/)
  })
})

describe('renderExtraEnv', () => {
  it('renders nothing when absent', () => {
    expect(renderExtraEnv()).toBe('')
  })

  it('renders KEY=value list entries', () => {
    expect(renderExtraEnv({ IRIS_BRAND: 'nimbleco' }))
      .toBe('      - IRIS_BRAND=nimbleco\n')
  })

  it('refuses a newline in a key or value', () => {
    expect(() => renderExtraEnv({ A: 'x\n      - B=y' })).toThrow(/newline/)
  })

  it('refuses a key that is not a valid env var name', () => {
    expect(() => renderExtraEnv({ 'not a key': 'x' })).toThrow(/valid environment variable name/)
  })

  // --- reserved names -------------------------------------------------------
  //
  // extraEnv is emitted AFTER the generated `environment:` block, and a compose
  // `environment:` entry outranks `env_file`. So without a denylist an extraEnv
  // key can (a) override the pinned HOME the generator sets specifically to
  // avoid the EACCES "Provider authentication failed" credential-probe failure,
  // and (b) silently replace a surface allowlist that the settings page still
  // renders from the .env — the console showing one policy, the container
  // running another. Both are refused, not dropped: dropping a key someone
  // wrote is its own false audit trail.

  it('refuses HOME and HERMES_HOME — the generated block sets them and loses', () => {
    expect(() => renderExtraEnv({ HOME: '/tmp' })).toThrow(/reserved/)
    expect(() => renderExtraEnv({ HERMES_HOME: '/tmp' })).toThrow(/reserved/)
  })

  it('refuses HERMES_AGENT_NAME — it is the agent identity HSM policy keys on', () => {
    expect(() => renderExtraEnv({ HERMES_AGENT_NAME: 'someone-else' })).toThrow(/reserved/)
  })

  it('refuses process-level code-execution levers', () => {
    for (const key of ['PATH', 'LD_PRELOAD', 'LD_LIBRARY_PATH']) {
      expect(() => renderExtraEnv({ [key]: '/evil' })).toThrow(/reserved/)
    }
  })

  it('refuses surface credentials and admission allowlists — env_file loses to this block', () => {
    for (const key of [
      'TELEGRAM_ALLOWED_USERS',
      'SIGNAL_ALLOWED_USERS',
      'DISCORD_ALLOWED_CHANNELS',
      'DISCORD_BOT_TOKEN',
    ]) {
      expect(() => renderExtraEnv({ [key]: 'x' })).toThrow(/reserved/)
    }
  })

  it('still allows ordinary agent-specific env', () => {
    expect(renderExtraEnv({ IRIS_INTAKE_DIR: '/opt/iris-intake' }))
      .toBe('      - IRIS_INTAKE_DIR=/opt/iris-intake\n')
  })
})

// The validators exist so a caller about to WRITE can refuse first — the
// settings PUT renders the compose only after the .env and the resources
// overlay have landed, so a throw there is a 500 on top of partial state. They
// must therefore accept and reject exactly what the renderers do; a validator
// that is more permissive than its renderer is worse than no validator, because
// it converts "refused cleanly" into "passed the gate, then exploded".
describe('validateExtraMounts / validateExtraEnv agree with the renderers', () => {
  const CASES: Array<{ label: string; mounts?: ExtraMount[]; env?: Record<string, string> }> = [
    { label: 'nothing configured' },
    { label: 'empty collections', mounts: [], env: {} },
    { label: 'valid mounts + env', mounts: [SPOOL, PACKAGE], env: { IRIS_BRAND: 'nimbleco' } },
    { label: 'relative host path', mounts: [{ hostPath: 'nope', containerPath: '/b' }] },
    { label: 'newline in a path', mounts: [{ hostPath: '/a\n x: y', containerPath: '/b' }] },
    { label: 'colon in a path', mounts: [{ hostPath: '/a:/b:rw', containerPath: '/b' }] },
    { label: 'empty path', mounts: [{ hostPath: '', containerPath: '/b' }] },
    { label: 'bad mode', mounts: [{ hostPath: '/a', containerPath: '/b', mode: 'z' as 'ro' }] },
    { label: 'reserved env name', env: { HOME: '/tmp' } },
    { label: 'invalid env name', env: { 'not a key': 'x' } },
    { label: 'newline in env value', env: { A: 'x\n      - B=y' } },
  ]

  for (const { label, mounts, env } of CASES) {
    it(`${label}: validator verdict matches render outcome`, () => {
      let renderThrew: string | null = null
      try {
        renderExtraMounts(mounts)
        renderExtraEnv(env)
      } catch (err) {
        renderThrew = (err as Error).message
      }
      const verdict = validateExtraMounts(mounts) ?? validateExtraEnv(env)
      expect(verdict).toBe(renderThrew)
    })
  }

  it('refuses a non-array extraMounts instead of crashing on .map', () => {
    // harnesses.json is hand-edited; a bare object here used to reach .map().
    expect(validateExtraMounts({ hostPath: '/a' } as unknown as ExtraMount[]))
      .toMatch(/must be an array/)
    expect(() => renderExtraMounts({ hostPath: '/a' } as unknown as ExtraMount[]))
      .toThrow(/must be an array/)
  })
})

describe('generateStandaloneCompose with extra mounts', () => {
  for (const [label, vpnEnabled] of [['plain', false], ['VPN', true]] as const) {
    describe(label, () => {
      it('emits the mounts and env into the hermes service blocks', () => {
        const compose = generateStandaloneCompose(agentName, port, dataDir, {
          vpnEnabled,
          extraMounts: [SPOOL, PACKAGE],
          extraEnv: { IRIS_INTAKE_DIR: '/opt/iris-intake', IRIS_BRAND: 'nimbleco' },
        })
        const volumes = listEntries(compose, `hermes-${agentName}`, 'volumes')
        const environment = listEntries(compose, `hermes-${agentName}`, 'environment')

        expect(volumes).toContain('/Users/juni/.iris/nimbleco/intake:/opt/iris-intake:rw')
        expect(volumes).toContain('/Users/juni/iris-gates/nimbleco:/opt/iris:ro')
        // The standard mounts survive alongside them.
        expect(volumes).toContain(`${dataDir}:/opt/data`)
        expect(environment).toContain('IRIS_INTAKE_DIR=/opt/iris-intake')
        expect(environment).toContain('IRIS_BRAND=nimbleco')
        expect(environment).toContain('HERMES_HOME=/opt/data')
        // command: must still follow the volumes block, not be swallowed by it.
        expect(compose).toContain('    command: gateway')
      })

      it('is byte-identical to the old output when no extras are configured', () => {
        // The regression guard for every existing agent: adding this feature
        // must not perturb a compose file that does not use it.
        const without = generateStandaloneCompose(agentName, port, dataDir, { vpnEnabled })
        const withEmpty = generateStandaloneCompose(agentName, port, dataDir, {
          vpnEnabled, extraMounts: [], extraEnv: {},
        })
        expect(withEmpty).toBe(without)
      })

      it('fails generation rather than emitting a malformed mount', () => {
        expect(() => generateStandaloneCompose(agentName, port, dataDir, {
          vpnEnabled,
          extraMounts: [{ hostPath: '/a\n    privileged: true', containerPath: '/b' }],
        })).toThrow(/newline/)
      })
    })
  }

  // NOTE ON SCOPE: this asserts only that the generator is deterministic — it
  // calls one pure function twice with one object, so it would stay green even
  // if nothing ever passed extraMounts to it. The claim that actually matters
  // ("a settings PUT re-renders the configured mounts") lives where the fields
  // are carried: settings/route.test.ts asserts on the options object reaching
  // generateCompose. Do not let this test stand in for that one.
  it('is deterministic across regenerations (see note: route.test.ts owns the real claim)', () => {
    const options = {
      extraMounts: [SPOOL, PACKAGE],
      extraEnv: { IRIS_INTAKE_DIR: '/opt/iris-intake' },
    }
    const first = generateStandaloneCompose(agentName, port, dataDir, options)
    const regenerated = generateStandaloneCompose(agentName, port, dataDir, options)
    expect(regenerated).toBe(first)
    expect(regenerated).toContain('/opt/iris-intake:rw')
  })
})
