/**
 * Standalone Docker Compose generation for Hermes agents.
 * Extracted from harness.ts to support VPN (WireGuard + Camofox) sidecar configuration.
 *
 * NOTE: s6-overlay handles privilege dropping internally — never set `user:` in compose.
 * Required caps: CHOWN, DAC_OVERRIDE, SETGID, SETUID (for s6), NET_BIND_SERVICE (for gateway).
 * Do NOT set read_only, no-new-privileges, or noexec tmpfs — s6 writes executables to /run.
 */

export interface ComposeOptions {
  imageOrBuild?: { image: string } | { build: string }
  defaultImage?: string
  vpnEnabled?: boolean
  camofoxImage?: string
  /**
   * Host interface to bind the human-facing VNC port to. The VNC port (noVNC,
   * container 6080) is used ONLY by a human during CAPTCHA escalation — the
   * agent never connects to it — so binding it to loopback by default keeps it
   * off the LAN/tailnet/internet. Set to a Tailscale IP/hostname to allow remote
   * human escalation. Defaults to '127.0.0.1'.
   */
  vncBindHost?: string
}

export function generateStandaloneCompose(
  agentName: string,
  port: number,
  agentDataDir: string,
  options?: ComposeOptions,
): string {
  const { imageOrBuild, defaultImage, vpnEnabled, camofoxImage, vncBindHost } = options ?? {}
  const resolved = imageOrBuild ?? { image: defaultImage || 'ghcr.io/nimblecoai/hermes-agent:latest' }
  const sourceBlock = 'image' in resolved
    ? `    image: ${resolved.image}`
    : `    build:\n      context: ${resolved.build}\n      dockerfile: Dockerfile`

  if (vpnEnabled) {
    return generateVpnCompose(agentName, port, agentDataDir, sourceBlock, camofoxImage, vncBindHost)
  }

  return generatePlainCompose(agentName, port, agentDataDir, sourceBlock)
}

function generatePlainCompose(
  agentName: string,
  port: number,
  agentDataDir: string,
  sourceBlock: string,
): string {
  return `# Generated by hermes-swarm-map — agent: ${agentName}
services:
  hermes-${agentName}:
${sourceBlock}
    container_name: hermes-${agentName}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ${agentDataDir}/.env
    ports:
      - published: ${port}
        target: 8642
    volumes:
      - ${agentDataDir}:/opt/data
    command: gateway
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
      - SETGID
      - SETUID
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'

networks:
  default:
    name: hermes-${agentName}
`
}

function generateVpnCompose(
  agentName: string,
  port: number,
  agentDataDir: string,
  sourceBlock: string,
  camofoxImage?: string,
  vncBindHost: string = '127.0.0.1',
): string {
  const camofoxPort = port + 1000
  const vncPort = port + 2000

  return `# Generated by hermes-swarm-map — agent: ${agentName} (VPN mode)
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-${agentName}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ${agentDataDir}/wg-config:/config
    ports:
      - published: ${port}
        target: 8642
      - published: ${camofoxPort}
        target: 9377
      # VNC is human-only (CAPTCHA escalation); bind to loopback by default so it
      # is not exposed on the LAN/tailnet. Set vncBindHost to a Tailscale address
      # to allow remote human escalation.
      - host_ip: ${vncBindHost}
        published: ${vncPort}
        target: 6080

  camofox:
    image: ${camofoxImage || 'ghcr.io/nimblecoai/camofox:latest'}
    container_name: camofox-${agentName}
    restart: unless-stopped
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      - CAMOFOX_PORT=9377
      - ENABLE_VNC=true
      - VNC_BIND=0.0.0.0
      - VNC_RESOLUTION=1280x720
    volumes:
      - ${agentDataDir}/.camofox:/data

  hermes-${agentName}:
${sourceBlock}
    container_name: hermes-${agentName}
    restart: unless-stopped
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ${agentDataDir}/.env
    volumes:
      - ${agentDataDir}:/opt/data
    command: gateway
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
      - SETGID
      - SETUID
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'

networks:
  default:
    name: hermes-${agentName}
`
}
