import fs from 'fs'
import path from 'path'
import os from 'os'
import { execSync } from 'child_process'
import type { Harness, HarnessStatus, HabitatTier, RestartMode } from '@/lib/types'
import { generateDefaultConfig } from '@/lib/templates/config-yaml'
import type { Storage } from './storage'
import type { DockerService } from './docker'
import type { AuditService } from './audit'
import type { ConfigService } from './config'
import { getCostToday, getInvocationsToday } from './usage'
import { markRestarting, isRestarting, clearRestarting } from './restart-tracker'
import { installBaselineTemplates } from './templates'
import type { ToolsService } from './tools'
import { generateStandaloneCompose } from './harness-compose'
import { hsmBaseUrl } from './hsm-url'

const HARNESSES_FILE = 'harnesses.json'

// Services that are infrastructure, not Hermes agents — skip during discovery
const EXCLUDED_SERVICES = new Set(['litellm', 'vertex-proxy'])

// Default port for new agents — Hermes standard is 8642+
const BASE_PORT = 8642
const PORT_STEP = 10

// Parse a .env file into key=value pairs
function parseEnvFilePairs(envPath: string): Record<string, string> {
  const result: Record<string, string> = {}
  try {
    const content = fs.readFileSync(envPath, 'utf-8')
    for (const rawLine of content.split('\n')) {
      const line = rawLine.trim()
      if (!line || line.startsWith('#')) continue
      const eq = line.indexOf('=')
      if (eq === -1) continue
      const varName = line.slice(0, eq).trim()
      const value = line.slice(eq + 1).trim().replace(/^["']|["']$/g, '')
      if (varName && value) result[varName] = value
    }
  } catch {}
  return result
}

// Scan compose dirs AND live Docker port bindings to find next available port
function nextAvailablePort(composeBaseDir: string): number {
  const usedPorts = new Set<number>()
  // Scan standalone compose files
  try {
    const entries = fs.readdirSync(composeBaseDir, { withFileTypes: true })
    for (const entry of entries) {
      if (!entry.isDirectory()) continue
      const composePath = path.join(composeBaseDir, entry.name, 'docker-compose.yml')
      try {
        const content = fs.readFileSync(composePath, 'utf-8')
        const portMatch = content.match(/published:\s*(\d+)/g)
        if (portMatch) {
          for (const m of portMatch) {
            const p = parseInt(m.replace('published:', '').trim(), 10)
            if (!isNaN(p)) usedPorts.add(p)
          }
        }
      } catch {}
    }
  } catch {}
  // Also scan live Docker containers for published ports (catches monolithic compose)
  try {
    const output = execSync('docker ps --format "{{.Ports}}"', { timeout: 5000 }).toString()
    for (const match of output.matchAll(/0\.0\.0\.0:(\d+)->/g)) {
      usedPorts.add(parseInt(match[1], 10))
    }
  } catch {}
  let port = BASE_PORT
  while (usedPorts.has(port)) {
    port += PORT_STEP
  }
  return port
}

// Directories to skip when duplicating an agent (caches, build artifacts, ephemeral state)
const COPY_SKIP_DIRS = new Set(['.cache', 'node_modules', '__pycache__', '.venv'])

// Surface-specific env vars stripped from duplicates to prevent two harnesses sharing one surface
const SURFACE_ENV_VARS = [
  'SIGNAL_ACCOUNT', 'SIGNAL_HTTP_URL', 'SIGNAL_ALLOWED_USERS', 'SIGNAL_GROUP_ALLOWED_USERS',
  'TELEGRAM_BOT_TOKEN', 'TELEGRAM_ALLOWED_USERS', 'TELEGRAM_GROUP_ALLOWED_CHATS',
  'MATTERMOST_URL', 'MATTERMOST_TOKEN', 'MATTERMOST_ALLOWED_CHANNELS', 'MATTERMOST_ALLOWED_USERS',
]

// Recursively copy a directory (sync — used by duplicateOverlay for full agent dir copies)
function copyDirRecursive(src: string, dest: string): void {
  fs.mkdirSync(dest, { recursive: true })
  const entries = fs.readdirSync(src, { withFileTypes: true })
  for (const entry of entries) {
    if (COPY_SKIP_DIRS.has(entry.name)) continue
    const srcPath = path.join(src, entry.name)
    const destPath = path.join(dest, entry.name)
    try {
      if (entry.isSymbolicLink()) {
        const target = fs.readlinkSync(srcPath)
        fs.symlinkSync(target, destPath)
      } else if (entry.isDirectory()) {
        copyDirRecursive(srcPath, destPath)
      } else {
        fs.copyFileSync(srcPath, destPath)
      }
    } catch {
      // Skip files that vanish during copy (volatile caches, broken symlinks)
    }
  }
}

// Write scaffold files for a brand-new agent data directory
async function scaffoldAgentDir(dataDir: string, name: string, port: number): Promise<void> {
  fs.mkdirSync(dataDir, { recursive: true })

  // .env with placeholder API key section
  const hsmUrl = hsmBaseUrl()
  const envContent = `# Hermes Agent: ${name}
# Generated by hermes-swarm-map

ANTHROPIC_API_KEY=
API_SERVER_PORT=${port}

# HSM policy endpoint
HSM_URL=${hsmUrl}
SWARM_MAP_POLICY_URL=${hsmUrl}

# Agent identity & memory
HERMES_MEMORY_SCOPE=channel
HERMES_AGENT_NAME=${name}
HERMES_HOME_CHANNEL=

# Web extraction (self-hosted Firecrawl — no API key needed)
FIRECRAWL_API_URL=http://host.docker.internal:3002

# Platform integration (uncomment as needed)
# MATTERMOST_TOKEN=
# MATTERMOST_URL=
# MATTERMOST_ALLOWED_USERS=
# MATTERMOST_ALLOWED_CHANNELS=
# TELEGRAM_BOT_TOKEN=

# Policy defaults (secure by default)
HERMES_DM_POLICY=approved-only
HERMES_APPROVAL_ADMIN_ONLY=true
SIGNAL_REQUIRE_MENTION=true
TELEGRAM_REQUIRE_MENTION=true
MATTERMOST_REQUIRE_MENTION=true
SIGNAL_GROUP_INVITE_POLICY=approved-only
`
  const envPath = path.join(dataDir, '.env')
  if (!fs.existsSync(envPath)) {
    fs.writeFileSync(envPath, envContent, { mode: 0o600 })
  }

  // config.yaml with opinionated defaults
  const configContent = generateDefaultConfig({
    provider: 'anthropic',
    primaryModel: 'claude-sonnet-4-5',
  })
  const configPath = path.join(dataDir, 'config.yaml')
  if (!fs.existsSync(configPath)) {
    fs.writeFileSync(configPath, configContent, 'utf-8')
  }

  // SOUL.md with operational awareness template
  const soulPath = path.join(dataDir, 'SOUL.md')
  if (!fs.existsSync(soulPath)) {
    const soulContent = `# ${name}

You are **${name}**, a Hermes agent in a multi-tenant deployment managed by Hermes Swarm Map.

## How You Work

**Multi-platform:** You serve users across Signal, Telegram, Mattermost, and other platforms simultaneously. Each platform connection is independent.

**Memory isolation:** Your memory is scoped per-context. What you learn in one group chat stays in that group. You maintain separate context for each conversation thread. If someone asks "what did we talk about last time?" — you recall only what happened in THAT specific chat.

**Session lifecycle:** Your conversations reset after 24 hours of inactivity or at 4 AM daily. This keeps you fast and prevents runaway costs. Important context is preserved in your per-context memory.

**Skills are global:** Skills you learn or create are available across all your conversations. A skill learned in one group benefits everyone.

**Group approval:** You only respond in groups that your admin has approved. If you're added to a new group, you'll check with HSM before engaging.

## Behavioral Defaults

- Be helpful, direct, and honest
- When you don't know something, say so clearly
- Never reference or leak information between different conversations
- You can share that you run on Hermes if asked about your system
- Use \`/model\` to check or switch your AI model
- Use \`/memory\` to review what you remember about this conversation
- If you're unsure whether something is appropriate to share across contexts, don't

## Your Admin

Your admin manages you through HSM. They can:
- Approve/deny groups you can participate in
- Monitor your usage and costs
- Update your configuration and model
- Manage your API keys and budget

## Personality

Customize this section to give ${name} a distinct voice, tone, and purpose.
What kind of assistant should ${name} be? Formal? Casual? Technical? Creative?
`
    fs.writeFileSync(soulPath, soulContent, 'utf-8')
  }

  // BOOT.md with startup checklist template
  const bootPath = path.join(dataDir, 'BOOT.md')
  if (!fs.existsSync(bootPath)) {
    const bootContent = `# Boot Checklist

On startup, verify your operational readiness:

1. **Check HSM connection** — Can you reach your management server? If not, note it but continue (you can still operate, just without group policy updates).

2. **Review your memory** — Check if you have any persistent memories from previous sessions. If this is your first boot, that's expected.

3. **Verify skills** — Run a quick skills check. Note any skills that failed to load.

4. **Status report** — If everything is nominal, reply with [SILENT]. Only report if something needs attention.

If this is your very first startup ever, introduce yourself briefly in your home channel (if configured).
`
    fs.writeFileSync(bootPath, bootContent, 'utf-8')
  }

  // memories directory
  fs.mkdirSync(path.join(dataDir, 'memories'), { recursive: true })

  // Install baseline plugins and hooks from templates
  await installBaselineTemplates(dataDir)
}

function expandPath(p: string): string {
  return p.replace(/^~/, os.homedir())
}

// Resolve image or build context from settings
function resolveImageOrBuild(settings?: { useLocalBuild?: boolean; hermesDir?: string }): { image: string } | { build: string } | undefined {
  if (!settings?.useLocalBuild || !settings.hermesDir) return undefined
  const resolved = expandPath(settings.hermesDir)
  try {
    const dockerfilePath = path.join(resolved, 'Dockerfile')
    if (fs.existsSync(dockerfilePath)) {
      return { build: resolved }
    }
  } catch {}
  return undefined
}

function containerNameToHarnessName(containerName: string): string {
  // hermes-personal → personal, seraph-thinker → seraph-thinker
  return containerName.replace(/^hermes-/, '')
}

function stateToStatus(state: string): HarnessStatus {
  switch (state) {
    case 'running': return 'running'
    case 'exited': return 'stopped'
    case 'restarting': return 'error'
    case 'created': return 'idle'
    default: return 'stopped'
  }
}

export function readModelConfig(dataDir: string): string[] {
  try {
    const configPath = path.join(dataDir, 'config.yaml')
    const content = fs.readFileSync(configPath, 'utf-8')
    const lines = content.split('\n')

    const models: string[] = []
    let inModelSection = false
    let inAuxSection = false

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]
      const trimmed = line.trim()

      // Detect top-level sections (no leading spaces)
      if (/^model:/.test(line)) {
        inModelSection = true
        inAuxSection = false
        continue
      }
      if (/^auxiliary:/.test(line)) {
        inAuxSection = true
        inModelSection = false
        continue
      }
      // Any new top-level key ends both sections
      if (/^\w/.test(line) && !trimmed.startsWith('#')) {
        inModelSection = false
        inAuxSection = false
      }

      if (inModelSection) {
        const defaultMatch = trimmed.match(/^default:\s*(.+)$/)
        if (defaultMatch) {
          const val = defaultMatch[1].trim().replace(/^["']|["']$/g, '')
          if (val && !models.includes(val)) {
            models.unshift(val) // primary model goes first
          }
        }
        const fallbackMatch = trimmed.match(/^fallback:\s*(.+)$/)
        if (fallbackMatch) {
          const val = fallbackMatch[1].trim().replace(/^["']|["']$/g, '')
          if (val && !models.includes(val)) {
            models.push(val)
          }
        }
      }

      // Auxiliary models — look for `model:` under nested keys
      if (inAuxSection) {
        const modelMatch = trimmed.match(/^model:\s*(.+)$/)
        if (modelMatch) {
          const val = modelMatch[1].trim().replace(/^["']|["']$/g, '')
          if (val && !models.includes(val)) {
            models.push(val)
          }
        }
      }
    }

    return models
  } catch {
    return []
  }
}

export type FallbackProvider = {
  provider: string
  model: string
  base_url?: string
  api_key?: string
}

export function readFallbackProviders(dataDir: string): FallbackProvider[] {
  try {
    const configPath = path.join(dataDir, 'config.yaml')
    const content = fs.readFileSync(configPath, 'utf-8')
    const lines = content.split('\n')

    const providers: FallbackProvider[] = []
    let inSection = false
    let current: Partial<FallbackProvider> | null = null

    for (const line of lines) {
      const trimmed = line.trim()

      // Detect the fallback_providers: top-level key
      if (/^fallback_providers:\s*$/.test(line) || /^fallback_providers:$/.test(line.trim())) {
        inSection = true
        continue
      }

      // Any new top-level key ends the section
      if (inSection && /^\w/.test(line) && !trimmed.startsWith('#')) {
        inSection = false
        // Flush last entry
        if (current?.provider && current?.model) {
          const entry: FallbackProvider = { provider: current.provider, model: current.model }
          if (current.base_url) entry.base_url = current.base_url
          if (current.api_key) entry.api_key = current.api_key
          providers.push(entry)
        }
        current = null
        continue
      }

      if (!inSection) continue

      // New list item starts with "- "
      if (trimmed.startsWith('- ')) {
        // Flush previous entry
        if (current?.provider && current?.model) {
          const entry: FallbackProvider = { provider: current.provider, model: current.model }
          if (current.base_url) entry.base_url = current.base_url
          if (current.api_key) entry.api_key = current.api_key
          providers.push(entry)
        }
        current = {}
        // Parse the key on the same line as "- "
        const rest = trimmed.slice(2).trim()
        const kv = rest.match(/^(\w+):\s*(.+)$/)
        if (kv) {
          const key = kv[1] as keyof FallbackProvider
          const val = kv[2].trim().replace(/^["']|["']$/g, '')
          if (val) (current as Record<string, string>)[key] = val
        }
        continue
      }

      // Continuation line for current entry (indented, no "- ")
      if (current && trimmed) {
        const kv = trimmed.match(/^(\w+):\s*(.+)$/)
        if (kv) {
          const key = kv[1] as keyof FallbackProvider
          const val = kv[2].trim().replace(/^["']|["']$/g, '')
          if (val) (current as Record<string, string>)[key] = val
        }
      }
    }

    // Flush last entry
    if (current?.provider && current?.model) {
      const entry: FallbackProvider = { provider: current.provider, model: current.model }
      if (current.base_url) entry.base_url = current.base_url
      if (current.api_key) entry.api_key = current.api_key
      providers.push(entry)
    }

    return providers
  } catch {
    return []
  }
}

export function readModelProvider(dataDir: string): string {
  try {
    const configPath = path.join(dataDir, 'config.yaml')
    const content = fs.readFileSync(configPath, 'utf-8')
    const lines = content.split('\n')

    let inModelSection = false
    for (const line of lines) {
      const trimmed = line.trim()
      if (/^model:/.test(line)) { inModelSection = true; continue }
      if (/^\w/.test(line) && !trimmed.startsWith('#')) { inModelSection = false }
      if (inModelSection) {
        const provMatch = trimmed.match(/^provider:\s*(.+)$/)
        if (provMatch) return provMatch[1].trim().replace(/^["']|["']$/g, '')
      }
    }
    return ''
  } catch {
    return ''
  }
}

function readSoul(dataDir: string, maxChars = 200): string {
  try {
    const soulPath = path.join(dataDir, 'SOUL.md')
    const content = fs.readFileSync(soulPath, 'utf-8')
    // Strip markdown headers/lines, grab first meaningful text
    const lines = content
      .split('\n')
      .map((l) => l.trim())
      .filter((l) => l && !l.startsWith('#') && !l.startsWith('*') && !l.startsWith('---'))
    const text = lines.join(' ').slice(0, maxChars)
    return text || ''
  } catch {
    return ''
  }
}

function getComposeFilesForDir(hermesDir: string): string[] {
  const expanded = expandPath(hermesDir)
  try {
    const entries = fs.readdirSync(expanded)
    return entries
      .filter((f) => f.startsWith('docker-compose') && f.endsWith('.yml'))
      .map((f) => path.join(expanded, f))
  } catch {
    return []
  }
}

function getServicesFromComposeFile(composeFile: string): string[] {
  try {
    const output = execSync(
      `docker compose -f ${composeFile} config --services`,
      { stdio: 'pipe', timeout: 10000 }
    ).toString()
    return output.trim().split('\n').filter((s) => s.trim())
  } catch {
    return []
  }
}

// Map service name to the data directory where its SOUL.md lives
export function guessDataDir(serviceName: string, containerName: string): string {
  // hermes-personal → ~/.hermes (the default/personal instance)
  // hermes-osint → ~/.hermes-osint
  // seraph-thinker → ~/.hermes-seraph-thinker
  const home = os.homedir()
  if (containerName === 'hermes-personal' || serviceName === 'hermes-personal') {
    return path.join(home, '.hermes')
  }
  if (!serviceName) {
    return path.join(home, '.hermes-' + (containerName || 'unknown'))
  }
  if (serviceName.startsWith('hermes-')) {
    return path.join(home, '.' + serviceName)
  }
  // seraph-* agents
  if (serviceName.startsWith('seraph-')) {
    return path.join(home, '.hermes-' + serviceName)
  }
  return path.join(home, '.hermes-' + serviceName)
}

export class HarnessService {
  private toolsService?: ToolsService

  constructor(
    private storage: Storage,
    private docker: DockerService,
    private audit: AuditService,
    private config?: ConfigService,
  ) {}

  /** Inject ToolsService after construction to break circular init dependency */
  setToolsService(toolsService: ToolsService): void {
    this.toolsService = toolsService
  }

  // Cache for auto-discovered tools per harness name — avoids re-scanning config.yaml on every API call
  private toolsDiscoveryCache = new Map<string, { tools: string[]; ts: number }>()
  private static TOOLS_CACHE_TTL_MS = 60_000 // 1 minute

  /**
   * Auto-discover tools for a harness by scanning its config.yaml and skills dir.
   * Results are cached for TOOLS_CACHE_TTL_MS to avoid filesystem reads on every request.
   * Returns undefined if ToolsService is not wired up.
   */
  private autoDiscoverTools(harnessName: string): string[] | undefined {
    if (!this.toolsService) return undefined

    const cached = this.toolsDiscoveryCache.get(harnessName)
    if (cached && Date.now() - cached.ts < HarnessService.TOOLS_CACHE_TTL_MS) {
      return cached.tools
    }

    const tools = this.toolsService.discoverForHarness(harnessName)
    this.toolsDiscoveryCache.set(harnessName, { tools, ts: Date.now() })
    return tools
  }

  // Load stored overlays — tier, tools, keys, and other user-configured fields
  private loadOverlays(): Record<string, Partial<Harness>> {
    const stored = this.storage.read<Harness[]>(HARNESSES_FILE, [])
    const overlays: Record<string, Partial<Harness>> = {}
    for (const h of stored) {
      overlays[h.id] = h
    }
    return overlays
  }

  // Write overlays back — only persists user-configured fields, not live Docker state
  private saveOverlays(harnesses: Harness[]): void {
    this.storage.write(HARNESSES_FILE, harnesses)
  }

  discover(): { harnesses: Harness[]; error?: string } {
    if (!this.docker.isAvailable()) {
      return { harnesses: [], error: 'Docker is not available' }
    }

    const settings = this.config?.getSettings()
    const hermesDir = settings?.hermesDir ?? process.env.HERMES_DIR ?? '~/hermes-swarm'
    const configuredFiles = settings?.composeFiles ?? []

    // Determine which compose files to scan
    const composeFiles =
      configuredFiles.length > 0
        ? configuredFiles.map(expandPath)
        : getComposeFilesForDir(hermesDir)

    // Also scan standalone compose files created by Swarm Map
    const swarmMapDataDir = settings?.dataDir
      ? expandPath(settings.dataDir)
      : path.join(os.homedir(), '.hermes-swarm-map')
    const standaloneDir = path.join(swarmMapDataDir, 'compose')
    try {
      const dirs = fs.readdirSync(standaloneDir, { withFileTypes: true })
      for (const d of dirs) {
        if (!d.isDirectory()) continue
        const cf = path.join(standaloneDir, d.name, 'docker-compose.yml')
        if (fs.existsSync(cf) && !composeFiles.includes(cf)) {
          composeFiles.push(cf)
        }
      }
    } catch {}

    if (composeFiles.length === 0) {
      return { harnesses: [], error: `No docker-compose*.yml files found in ${hermesDir}` }
    }

    const overlays = this.loadOverlays()

    // Build a map of container name → live state via `docker compose ls` + per-project inspect
    // Use the project name "hermes-swarm" since that's how both files are deployed
    const liveContainers: Record<string, {
      state: string
      ports: Array<{ published: number; target: number }>
      composeFile: string
      serviceName: string
    }> = {}

    // Find the project names for our compose files via `docker compose ls`
    const projects = this.docker.listComposeProjects()
    // Build a set of absolute config file paths we care about
    const wantedFiles = new Set(composeFiles.map((f) => expandPath(f)))

    for (const project of projects) {
      const matchingFiles = project.configFiles.filter((f) => wantedFiles.has(f))
      if (matchingFiles.length === 0) continue

      const containers = this.docker.inspectContainers(project.name)
      for (const c of containers) {
        if (EXCLUDED_SERVICES.has(c.service)) continue
        // Prefer the config file that was in our wanted set
        const composeFile = c.composeFile ?? matchingFiles[0]
        liveContainers[c.name] = {
          state: c.state,
          ports: c.ports,
          composeFile,
          serviceName: c.service,
        }
      }
    }

    // If project-based lookup gave nothing, fall back to per-file inspection
    if (Object.keys(liveContainers).length === 0) {
      for (const composeFile of composeFiles) {
        const containers = this.docker.inspectContainers(
          path.basename(path.dirname(composeFile))
        )
        // Also try direct file-based approach
        const raw = this.docker.listContainers(composeFile)
        for (const c of raw) {
          if (EXCLUDED_SERVICES.has(c.service)) continue
          liveContainers[c.name] = {
            state: c.state,
            ports: [],
            composeFile,
            serviceName: c.service,
          }
        }
        void containers // suppress unused warning
      }
    }

    // Batch stats for ALL containers in one Docker call (~2s total, not 10s per container)
    const allStats = this.docker.getAllContainerStats()

    const harnesses: Harness[] = []

    for (const [containerName, live] of Object.entries(liveContainers)) {
      const name = containerNameToHarnessName(containerName)
      const id = 'h_' + name.replace(/-/g, '_')

      // Only include containers that look like hermes agents or have an overlay
      const isHermes = containerName.startsWith('hermes-') || containerName.startsWith('seraph-')
      if (!isHermes && !overlays[id]) continue

      const dataDir = guessDataDir(live.serviceName, containerName)
      const persona = readSoul(dataDir)

      const stats = allStats[containerName] ?? { cpu: 0, memMiB: 0 }

      // Port: first published port
      const port = live.ports[0]?.published

      const overlay = overlays[id] ?? {}

      const harness: Harness = {
        // Discoverable fields
        id,
        name,
        runtime: 'hermes',
        status: stateToStatus(live.state),
        health: { errors: 0 },
        persona: persona || overlay.persona || `Hermes agent: ${name}`,
        lastSeen: Date.now(),
        cpu: stats.cpu,
        mem: stats.memMiB,
        composeFile: live.composeFile,
        serviceName: live.serviceName,
        // Overlay fields (user-configured) — fall back to sensible defaults
        tier: overlay.tier ?? 'individual',
        platform: overlay.platform ?? 'hermes',
        channel: overlay.channel ?? (port ? `:${port}` : ''),
        models: overlay.models?.length ? overlay.models : readModelConfig(dataDir),
        costToday: getCostToday(id),
        invocations: getInvocationsToday(id),
        tools: overlay.tools ?? this.autoDiscoverTools(name) ?? [],
        ...(overlay.health ? { health: overlay.health } : {}),
        ...(overlay.cacheState ? { cacheState: overlay.cacheState } : {}),
        ...(overlay.cacheAge !== undefined ? { cacheAge: overlay.cacheAge } : {}),
        ...(overlay.parentId ? { parentId: overlay.parentId } : {}),
      }

      // Override status based on restart tracker
      if (isRestarting(id)) {
        if (harness.status === 'running') {
          clearRestarting(id) // build completed successfully
        } else {
          harness.status = 'restarting'
        }
      }

      harnesses.push(harness)
    }

    // Sort: hermes-* first, then seraph-*
    harnesses.sort((a, b) => {
      const aIsSeraph = a.name.startsWith('seraph-') ? 1 : 0
      const bIsSeraph = b.name.startsWith('seraph-') ? 1 : 0
      if (aIsSeraph !== bIsSeraph) return aIsSeraph - bIsSeraph
      return a.name.localeCompare(b.name)
    })

    return { harnesses }
  }

  list(): Harness[] {
    const { harnesses } = this.discover()
    // Fall back to stored overlays if Docker discovery returned nothing
    if (harnesses.length === 0) {
      return this.storage.read<Harness[]>(HARNESSES_FILE, [])
    }

    // Include overlay-only entries that have no running container (e.g. duplicated but not started)
    const discoveredIds = new Set(harnesses.map((h) => h.id))
    const overlays = this.storage.read<Partial<Harness>[]>(HARNESSES_FILE, [])
    for (const overlay of overlays) {
      if (!overlay.id || discoveredIds.has(overlay.id)) continue
      harnesses.push({
        id: overlay.id,
        name: overlay.name ?? overlay.id.replace(/^h_/, '').replace(/_/g, '-'),
        runtime: 'hermes',
        status: 'stopped',
        health: { errors: 0 },
        persona: overlay.persona ?? '',
        lastSeen: 0,
        cpu: 0,
        mem: 0,
        tier: overlay.tier ?? 'individual',
        platform: overlay.platform ?? 'hermes',
        channel: overlay.channel ?? '',
        models: overlay.models ?? [],
        tools: overlay.tools ?? [],
        costToday: 0,
        invocations: 0,
        composeFile: overlay.composeFile,
        serviceName: overlay.serviceName,
      } as Harness)
    }

    return harnesses
  }

  get(id: string): Harness | undefined {
    return this.list().find((h) => h.id === id)
  }

  updateConfig(id: string, partial: Partial<Harness>): Harness | undefined {
    // Load existing overlays, merge, persist
    const overlays = this.storage.read<Harness[]>(HARNESSES_FILE, [])
    const index = overlays.findIndex((h) => h.id === id)
    if (index !== -1) {
      overlays[index] = { ...overlays[index], ...partial }
    } else {
      // New overlay entry — we need at least a skeleton
      const current = this.get(id)
      if (!current) return undefined
      overlays.push({ ...current, ...partial })
    }
    this.saveOverlays(overlays)
    return this.get(id)
  }

  restart(id: string, mode: RestartMode): void {
    const harness = this.get(id)
    if (!harness?.composeFile || !harness.serviceName) {
      throw new Error(`Harness ${id} has no compose file configured`)
    }
    markRestarting(id, mode)
    this.docker.restart(harness.composeFile, harness.serviceName, mode)
    this.audit.append({ who: 'admin', what: `restart:${mode}`, target: harness.name })
  }

  start(id: string): void {
    const harness = this.get(id)
    if (!harness?.composeFile || !harness.serviceName) {
      throw new Error(`Harness ${id} has no compose file configured`)
    }
    this.docker.start(harness.composeFile, harness.serviceName)
    this.audit.append({ who: 'admin', what: 'start', target: harness.name })
  }

  stop(id: string): void {
    const harness = this.get(id)
    if (!harness?.composeFile || !harness.serviceName) {
      throw new Error(`Harness ${id} has no compose file configured`)
    }
    this.docker.stop(harness.composeFile, harness.serviceName)
    this.audit.append({ who: 'admin', what: 'stop', target: harness.name })
  }

  async duplicateOverlay(sourceId: string, newName: string): Promise<Partial<Harness> | undefined> {
    const overlays = this.storage.read<Partial<Harness>[]>('harnesses.json', [])
    const source = overlays.find((h) => h.id === sourceId)
    if (!source) return undefined

    const newId = 'h_' + newName.replace(/-/g, '_').replace(/\s+/g, '_')

    // Reject if name or ID already exists
    if (overlays.some((h) => h.id === newId || h.name === newName)) {
      return undefined
    }

    // Determine agent dirs
    const sourceName = source.name ?? sourceId.replace(/^h_/, '').replace(/_/g, '-')
    const sourceDataDir = path.join(os.homedir(), `.hermes-${sourceName}`)
    const newDataDir = path.join(os.homedir(), `.hermes-${newName}`)

    // Settings for compose dir
    const settings = this.config?.getSettings()
    const swarmMapDataDir = settings?.dataDir
      ? expandPath(settings.dataDir)
      : path.join(os.homedir(), '.hermes-swarm-map')
    const composeBaseDir = path.join(swarmMapDataDir, 'compose')

    // Pick next available port
    const port = nextAvailablePort(composeBaseDir)

    // Copy source data directory if it exists, else scaffold fresh
    if (fs.existsSync(sourceDataDir) && !fs.existsSync(newDataDir)) {
      // Deep copy using recursive dir copy
      copyDirRecursive(sourceDataDir, newDataDir)
      // Update port and strip surface credentials from the new .env
      const newEnvPath = path.join(newDataDir, '.env')
      if (fs.existsSync(newEnvPath)) {
        let envContent = fs.readFileSync(newEnvPath, 'utf-8')
        envContent = envContent.replace(
          /^API_SERVER_PORT=.*/m,
          `API_SERVER_PORT=${port}`
        )
        // Remove surface-specific vars to avoid two harnesses bound to the same surface
        envContent = envContent
          .split('\n')
          .filter((line) => !SURFACE_ENV_VARS.some((v) => line.startsWith(`${v}=`)))
          .join('\n')
        fs.writeFileSync(newEnvPath, envContent, { mode: 0o600 })
      }
    } else if (!fs.existsSync(newDataDir)) {
      await scaffoldAgentDir(newDataDir, newName, port)
    }

    // Generate standalone compose for the duplicate
    const agentComposeDir = path.join(composeBaseDir, newName)
    fs.mkdirSync(agentComposeDir, { recursive: true })
    const composePath = path.join(agentComposeDir, 'docker-compose.yml')
    if (!fs.existsSync(composePath)) {
      fs.writeFileSync(composePath, generateStandaloneCompose(newName, port, newDataDir, { imageOrBuild: resolveImageOrBuild(settings), defaultImage: settings?.defaultImage }), 'utf-8')
    }

    const duplicate: Partial<Harness> = {
      ...source,
      id: newId,
      name: newName,
      channel: `:${port}`,
      composeFile: composePath,
      serviceName: `hermes-${newName}`,
      parentId: sourceId,
      platform: undefined, // reset — no surfaces connected yet
    }

    overlays.push(duplicate)
    this.storage.write('harnesses.json', overlays)

    this.audit.append({
      who: 'admin',
      what: 'duplicate',
      target: `${source.name ?? sourceId} → ${newName}`,
    })

    return duplicate
  }

  remove(id: string, deleteFiles: boolean): { removed: boolean; stopped: boolean; filesDeleted: boolean } {
    const overlays = this.storage.read<Partial<Harness>[]>(HARNESSES_FILE, [])
    const index = overlays.findIndex((h) => h.id === id)
    if (index === -1) return { removed: false, stopped: false, filesDeleted: false }

    const overlay = overlays[index]
    const name = overlay.name ?? id.replace(/^h_/, '').replace(/_/g, '-')
    let stopped = false
    let filesDeleted = false

    // Stop container if running
    if (overlay.composeFile && overlay.serviceName) {
      try {
        this.docker.stop(overlay.composeFile, overlay.serviceName)
        stopped = true
      } catch {
        // Container may not be running — that's fine
      }
    }

    // Remove overlay entry
    overlays.splice(index, 1)
    this.storage.write(HARNESSES_FILE, overlays)

    if (deleteFiles) {
      // Remove data directory
      const dataDir = path.join(os.homedir(), `.hermes-${name}`)
      if (fs.existsSync(dataDir)) {
        fs.rmSync(dataDir, { recursive: true, force: true })
        filesDeleted = true
      }
      // Remove compose directory
      if (overlay.composeFile) {
        const composeDir = path.dirname(overlay.composeFile)
        if (fs.existsSync(composeDir)) {
          fs.rmSync(composeDir, { recursive: true, force: true })
          filesDeleted = true
        }
      }
    }

    this.audit.append({
      who: 'admin',
      what: deleteFiles ? 'delete' : 'unregister',
      target: name,
    })

    return { removed: true, stopped, filesDeleted }
  }

  async createOverlay(input: { name: string; tier?: HabitatTier; platform?: string; channel?: string; models?: string[]; tools?: string[] }): Promise<Partial<Harness>> {
    const overlays = this.storage.read<Partial<Harness>[]>('harnesses.json', [])

    // Check for duplicate name
    const id = 'h_' + input.name.replace(/-/g, '_').replace(/\s+/g, '_')
    if (overlays.some((h) => h.id === id || h.name === input.name)) {
      throw new Error(`Harness "${input.name}" already exists`)
    }

    // Determine standalone compose directory from settings
    const settings = this.config?.getSettings()
    const swarmMapDataDir = settings?.dataDir
      ? expandPath(settings.dataDir)
      : path.join(os.homedir(), '.hermes-swarm-map')
    const composeBaseDir = path.join(swarmMapDataDir, 'compose')

    // Pick next available port
    const port = nextAvailablePort(composeBaseDir)

    // Agent data directory (where .env, config.yaml, SOUL.md live)
    const agentDir = path.join(os.homedir(), `.hermes-${input.name}`)

    // Scaffold agent data directory if it doesn't exist
    if (!fs.existsSync(agentDir)) {
      await scaffoldAgentDir(agentDir, input.name, port)
    }

    // Generate standalone compose file
    const agentComposeDir = path.join(composeBaseDir, input.name)
    fs.mkdirSync(agentComposeDir, { recursive: true })
    const composePath = path.join(agentComposeDir, 'docker-compose.yml')
    if (!fs.existsSync(composePath)) {
      fs.writeFileSync(composePath, generateStandaloneCompose(input.name, port, agentDir, { imageOrBuild: resolveImageOrBuild(settings), defaultImage: settings?.defaultImage }), 'utf-8')
    }

    const overlay: Partial<Harness> = {
      id,
      name: input.name,
      tier: input.tier ?? 'individual',
      platform: input.platform ?? 'hermes',
      channel: input.channel ?? `:${port}`,
      models: input.models ?? ['claude-sonnet-4-5'],
      tools: input.tools ?? [],
      composeFile: composePath,
      serviceName: `hermes-${input.name}`,
    }

    overlays.push(overlay)
    this.storage.write('harnesses.json', overlays)
    this.audit.append({ who: 'admin', what: 'create', target: input.name })
    return overlay
  }

  async importFromDir(sourceDir: string, name: string): Promise<{
    id?: string
    name: string
    sourceDir: string
    destDir: string
    changes: {
      copied: boolean
      envVarsAdded: string[]
      pluginsInstalled: string[]
      bootMdCreated: boolean
      composeGenerated: boolean
    }
  }> {
    // 1. Validate source directory
    const expandedSource = expandPath(sourceDir)
    if (!fs.existsSync(expandedSource)) {
      throw new Error(`Source directory not found: ${expandedSource}`)
    }
    const hasEnv = fs.existsSync(path.join(expandedSource, '.env'))
    const hasConfig = fs.existsSync(path.join(expandedSource, 'config.yaml'))
    if (!hasEnv && !hasConfig) {
      throw new Error(`Not a Hermes data directory: missing .env and config.yaml`)
    }

    // 2. Determine destination
    const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
    const destDir = slug === 'personal'
      ? path.join(os.homedir(), '.hermes')
      : path.join(os.homedir(), `.hermes-${slug}`)

    // 3. Copy source to managed location (fail if dest exists)
    let copied = false
    if (expandedSource !== destDir) {
      if (fs.existsSync(destDir)) {
        throw new Error(`Destination already exists: ${destDir}. Remove it first or choose a different name.`)
      }
      copyDirRecursive(expandedSource, destDir)
      copied = true
    }

    const workDir = destDir

    // 4. Patch .env — append missing HSM vars
    const hsmUrl = hsmBaseUrl()
    const requiredVars: Record<string, string> = {
      HSM_URL: hsmUrl,
      SWARM_MAP_POLICY_URL: hsmUrl,
      HERMES_AGENT_NAME: slug,
      HERMES_MEMORY_SCOPE: 'channel',
      HERMES_DM_POLICY: 'approved-only',
      HERMES_APPROVAL_ADMIN_ONLY: 'true',
      // Mention-only is the secure default for groups, matching newly-created
      // and deployed agents. Only applied when absent, so an imported agent that
      // explicitly set these stays as configured.
      SIGNAL_REQUIRE_MENTION: 'true',
      TELEGRAM_REQUIRE_MENTION: 'true',
      MATTERMOST_REQUIRE_MENTION: 'true',
    }

    const envPath = path.join(workDir, '.env')
    let envContent = ''
    try { envContent = fs.readFileSync(envPath, 'utf-8') } catch {}

    const envVarsAdded: string[] = []
    const existingVars = new Set(
      envContent.split('\n')
        .filter(l => !l.startsWith('#') && l.includes('='))
        .map(l => l.split('=')[0].trim())
    )

    const newLines: string[] = []
    for (const [key, value] of Object.entries(requiredVars)) {
      if (!existingVars.has(key)) {
        newLines.push(`${key}=${value}`)
        envVarsAdded.push(key)
      }
    }

    if (newLines.length > 0) {
      const separator = envContent.endsWith('\n') ? '' : '\n'
      envContent += `${separator}\n# HSM integration (added by import)\n${newLines.join('\n')}\n`
      fs.writeFileSync(envPath, envContent, { mode: 0o600 })
    }

    // 5. Install baseline plugins
    const installResults = await installBaselineTemplates(workDir)
    const pluginsInstalled = installResults
      .filter((r) => r.type === 'plugins' && r.installed)
      .map((r) => r.name)

    // 6. Write BOOT.md if not present
    let bootMdCreated = false
    const bootPath = path.join(workDir, 'BOOT.md')
    if (!fs.existsSync(bootPath)) {
      const bootContent = `# Boot Checklist

On startup, verify your operational readiness:

1. **Check HSM connection** — Can you reach your management server? If not, note it but continue (you can still operate, just without group policy updates).

2. **Review your memory** — Check if you have any persistent memories from previous sessions. If this is your first boot, that's expected.

3. **Verify skills** — Run a quick skills check. Note any skills that failed to load.

4. **Status report** — If everything is nominal, reply with [SILENT]. Only report if something needs attention.

If this is your very first startup ever, introduce yourself briefly in your home channel (if configured).
`
      fs.writeFileSync(bootPath, bootContent, 'utf-8')
      bootMdCreated = true
    }

    // 7. Generate standalone compose file
    let composeGenerated = false
    const settings = this.config?.getSettings()
    const swarmMapDataDir = settings?.dataDir
      ? expandPath(settings.dataDir)
      : path.join(os.homedir(), '.hermes-swarm-map')
    const composeBaseDir = path.join(swarmMapDataDir, 'compose')
    const agentComposeDir = path.join(composeBaseDir, slug)
    const composePath = path.join(agentComposeDir, 'docker-compose.yml')

    if (!fs.existsSync(composePath)) {
      fs.mkdirSync(agentComposeDir, { recursive: true })
      const existingPort = existingVars.has('API_SERVER_PORT')
        ? parseInt(envContent.match(/API_SERVER_PORT=(\d+)/)?.[1] || '0', 10)
        : 0
      const port = existingPort || nextAvailablePort(composeBaseDir)
      fs.writeFileSync(
        composePath,
        generateStandaloneCompose(slug, port, workDir, { imageOrBuild: resolveImageOrBuild(settings), defaultImage: settings?.defaultImage }),
        'utf-8'
      )
      composeGenerated = true
    }

    // 8. Read metadata from the copy for overlay registration
    let persona = ''
    try {
      const soulPath = path.join(workDir, 'SOUL.md')
      const content = fs.readFileSync(soulPath, 'utf-8')
      const lines = content
        .split('\n')
        .map((l) => l.trim())
        .filter((l) => l && !l.startsWith('#') && !l.startsWith('---'))
      persona = lines.join(' ').slice(0, 200)
    } catch {}

    const env = parseEnvFilePairs(path.join(workDir, '.env'))
    let platform = 'hermes'
    if (env['MATTERMOST_TOKEN'] || env['MATTERMOST_URL']) {
      platform = 'mattermost'
    } else if (env['TELEGRAM_BOT_TOKEN']) {
      platform = 'telegram'
    }
    const agentPort = env['API_SERVER_PORT'] ? parseInt(env['API_SERVER_PORT'], 10) : undefined
    const channel = agentPort ? `:${agentPort}` : ''

    const models = readModelConfig(workDir)

    let tools: string[] = []
    try {
      const skillsDir = path.join(workDir, 'skills')
      const entries = fs.readdirSync(skillsDir, { withFileTypes: true })
      tools = entries
        .filter((e) => e.isDirectory())
        .map((e) => e.name)
        .slice(0, 50)
    } catch {}

    // 9. Register overlay
    const overlay = await this.createOverlay({ name: slug, platform, channel, models })

    const patches: Partial<Harness> = {}
    if (persona) patches.persona = persona
    if (tools.length > 0) patches.tools = tools
    patches.composeFile = composePath
    patches.serviceName = `hermes-${slug}`

    if (Object.keys(patches).length > 0) {
      Object.assign(overlay, patches)
      const overlays = this.storage.read<Partial<Harness>[]>('harnesses.json', [])
      const idx = overlays.findIndex((h) => h.id === overlay.id)
      if (idx !== -1) {
        overlays[idx] = { ...overlays[idx], ...patches }
        this.storage.write('harnesses.json', overlays)
      }
    }

    return {
      id: overlay.id,
      name: slug,
      sourceDir: expandedSource,
      destDir,
      changes: {
        copied,
        envVarsAdded,
        pluginsInstalled,
        bootMdCreated,
        composeGenerated,
      },
    }
  }

  restartRunning(): { restarted: string[]; errors: Record<string, string> } {
    const running = this.list().filter((h) => h.status === 'running')
    const restarted: string[] = []
    const errors: Record<string, string> = {}
    for (const harness of running) {
      try {
        if (harness.composeFile && harness.serviceName) {
          this.docker.restart(harness.composeFile, harness.serviceName, 'quick')
          restarted.push(harness.id)
          this.audit.append({ who: 'admin', what: 'restart:quick', target: harness.name })
        }
      } catch (err) {
        errors[harness.id] = err instanceof Error ? err.message : String(err)
      }
    }
    return { restarted, errors }
  }
}
