import fs from 'fs'
import path from 'path'
import os from 'os'
import { execSync } from 'child_process'
import type { Harness, HarnessStatus, HabitatTier, RestartMode } from '@/lib/types'
import type { Storage } from './storage'
import type { DockerService } from './docker'
import type { AuditService } from './audit'
import type { ConfigService } from './config'
import { getCostToday } from './usage'

const HARNESSES_FILE = 'harnesses.json'

// Services that are infrastructure, not Hermes agents — skip during discovery
const EXCLUDED_SERVICES = new Set(['litellm', 'vertex-proxy'])

// Default port for new agents — Hermes standard is 8642+
const BASE_PORT = 8642
const PORT_STEP = 10

// Parse a .env file into key=value pairs
function parseEnvFilePairs(envPath: string): Record<string, string> {
  const result: Record<string, string> = {}
  try {
    const content = fs.readFileSync(envPath, 'utf-8')
    for (const rawLine of content.split('\n')) {
      const line = rawLine.trim()
      if (!line || line.startsWith('#')) continue
      const eq = line.indexOf('=')
      if (eq === -1) continue
      const varName = line.slice(0, eq).trim()
      const value = line.slice(eq + 1).trim().replace(/^["']|["']$/g, '')
      if (varName && value) result[varName] = value
    }
  } catch {}
  return result
}

// Scan existing standalone compose dirs to find next available port
function nextAvailablePort(composeBaseDir: string): number {
  const usedPorts = new Set<number>()
  try {
    const entries = fs.readdirSync(composeBaseDir, { withFileTypes: true })
    for (const entry of entries) {
      if (!entry.isDirectory()) continue
      const composePath = path.join(composeBaseDir, entry.name, 'docker-compose.yml')
      try {
        const content = fs.readFileSync(composePath, 'utf-8')
        const portMatch = content.match(/published:\s*(\d+)/g)
        if (portMatch) {
          for (const m of portMatch) {
            const p = parseInt(m.replace('published:', '').trim(), 10)
            if (!isNaN(p)) usedPorts.add(p)
          }
        }
      } catch {}
    }
  } catch {}
  let port = BASE_PORT
  while (usedPorts.has(port)) {
    port += PORT_STEP
  }
  return port
}

// Generate a standalone docker-compose.yml for a new agent
function generateStandaloneCompose(agentName: string, port: number, agentDataDir: string, imageOrBuild?: { image: string } | { build: string }): string {
  const resolved = imageOrBuild ?? { image: 'nousresearch/hermes-agent:latest' }
  const sourceBlock = 'image' in resolved
    ? `    image: ${resolved.image}`
    : `    build:\n      context: ${resolved.build}\n      dockerfile: Dockerfile`

  return `# Generated by hermes-swarm-map — agent: ${agentName}
services:
  hermes-${agentName}:
${sourceBlock}
    container_name: hermes-${agentName}
    restart: unless-stopped
    env_file:
      - ${agentDataDir}/.env
    ports:
      - published: ${port}
        target: 8642
    volumes:
      - ${agentDataDir}:/opt/data
    command: gateway
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - SYS_CHROOT

networks:
  default:
    name: hermes-${agentName}
`
}

// Recursively copy a directory
function copyDirRecursive(src: string, dest: string): void {
  fs.mkdirSync(dest, { recursive: true })
  const entries = fs.readdirSync(src, { withFileTypes: true })
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name)
    const destPath = path.join(dest, entry.name)
    if (entry.isDirectory()) {
      copyDirRecursive(srcPath, destPath)
    } else {
      fs.copyFileSync(srcPath, destPath)
    }
  }
}

// Write scaffold files for a brand-new agent data directory
function scaffoldAgentDir(dataDir: string, name: string, port: number): void {
  fs.mkdirSync(dataDir, { recursive: true })

  // .env with placeholder API key section
  const hsmPort = process.env.PORT || '3002'
  const envContent = `# Hermes Agent: ${name}
# Generated by hermes-swarm-map

ANTHROPIC_API_KEY=
API_SERVER_PORT=${port}

# Swarm Map policy endpoint
SWARM_MAP_POLICY_URL=http://host.docker.internal:${hsmPort}

# Agent identity & memory
HERMES_MEMORY_SCOPE=channel
HERMES_AGENT_NAME=${name}
HERMES_HOME_CHANNEL=

# Platform integration (uncomment as needed)
# MATTERMOST_TOKEN=
# MATTERMOST_URL=
# TELEGRAM_BOT_TOKEN=
`
  const envPath = path.join(dataDir, '.env')
  if (!fs.existsSync(envPath)) {
    fs.writeFileSync(envPath, envContent, { mode: 0o600 })
  }

  // config.yaml with minimal model config
  const configContent = `model:
  provider: anthropic
  default: claude-sonnet-4-5
`
  const configPath = path.join(dataDir, 'config.yaml')
  if (!fs.existsSync(configPath)) {
    fs.writeFileSync(configPath, configContent, 'utf-8')
  }

  // SOUL.md placeholder
  const soulPath = path.join(dataDir, 'SOUL.md')
  if (!fs.existsSync(soulPath)) {
    fs.writeFileSync(soulPath, `# ${name}\n\nDescribe this agent's purpose and personality here.\n`, 'utf-8')
  }

  // memories directory
  fs.mkdirSync(path.join(dataDir, 'memories'), { recursive: true })
}

function expandPath(p: string): string {
  return p.replace(/^~/, os.homedir())
}

// Resolve image or build context from settings
function resolveImageOrBuild(settings?: { useLocalBuild?: boolean; hermesDir?: string }): { image: string } | { build: string } | undefined {
  if (!settings?.useLocalBuild || !settings.hermesDir) return undefined
  const resolved = expandPath(settings.hermesDir)
  try {
    const dockerfilePath = path.join(resolved, 'Dockerfile')
    if (fs.existsSync(dockerfilePath)) {
      return { build: resolved }
    }
  } catch {}
  return undefined
}

function containerNameToHarnessName(containerName: string): string {
  // hermes-personal → personal, seraph-thinker → seraph-thinker
  return containerName.replace(/^hermes-/, '')
}

function stateToStatus(state: string): HarnessStatus {
  switch (state) {
    case 'running': return 'running'
    case 'exited': return 'stopped'
    case 'restarting': return 'error'
    case 'created': return 'idle'
    default: return 'stopped'
  }
}

export function readModelConfig(dataDir: string): string[] {
  try {
    const configPath = path.join(dataDir, 'config.yaml')
    const content = fs.readFileSync(configPath, 'utf-8')
    const lines = content.split('\n')

    const models: string[] = []
    let inModelSection = false
    let inAuxSection = false

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]
      const trimmed = line.trim()

      // Detect top-level sections (no leading spaces)
      if (/^model:/.test(line)) {
        inModelSection = true
        inAuxSection = false
        continue
      }
      if (/^auxiliary:/.test(line)) {
        inAuxSection = true
        inModelSection = false
        continue
      }
      // Any new top-level key ends both sections
      if (/^\w/.test(line) && !trimmed.startsWith('#')) {
        inModelSection = false
        inAuxSection = false
      }

      if (inModelSection) {
        const defaultMatch = trimmed.match(/^default:\s*(.+)$/)
        if (defaultMatch) {
          const val = defaultMatch[1].trim().replace(/^["']|["']$/g, '')
          if (val && !models.includes(val)) {
            models.unshift(val) // primary model goes first
          }
        }
        const fallbackMatch = trimmed.match(/^fallback:\s*(.+)$/)
        if (fallbackMatch) {
          const val = fallbackMatch[1].trim().replace(/^["']|["']$/g, '')
          if (val && !models.includes(val)) {
            models.push(val)
          }
        }
      }

      // Auxiliary models — look for `model:` under nested keys
      if (inAuxSection) {
        const modelMatch = trimmed.match(/^model:\s*(.+)$/)
        if (modelMatch) {
          const val = modelMatch[1].trim().replace(/^["']|["']$/g, '')
          if (val && !models.includes(val)) {
            models.push(val)
          }
        }
      }
    }

    return models
  } catch {
    return []
  }
}

export type FallbackProvider = {
  provider: string
  model: string
  base_url?: string
  api_key?: string
}

export function readFallbackProviders(dataDir: string): FallbackProvider[] {
  try {
    const configPath = path.join(dataDir, 'config.yaml')
    const content = fs.readFileSync(configPath, 'utf-8')
    const lines = content.split('\n')

    const providers: FallbackProvider[] = []
    let inSection = false
    let current: Partial<FallbackProvider> | null = null

    for (const line of lines) {
      const trimmed = line.trim()

      // Detect the fallback_providers: top-level key
      if (/^fallback_providers:\s*$/.test(line) || /^fallback_providers:$/.test(line.trim())) {
        inSection = true
        continue
      }

      // Any new top-level key ends the section
      if (inSection && /^\w/.test(line) && !trimmed.startsWith('#')) {
        inSection = false
        // Flush last entry
        if (current?.provider && current?.model) {
          const entry: FallbackProvider = { provider: current.provider, model: current.model }
          if (current.base_url) entry.base_url = current.base_url
          if (current.api_key) entry.api_key = current.api_key
          providers.push(entry)
        }
        current = null
        continue
      }

      if (!inSection) continue

      // New list item starts with "- "
      if (trimmed.startsWith('- ')) {
        // Flush previous entry
        if (current?.provider && current?.model) {
          const entry: FallbackProvider = { provider: current.provider, model: current.model }
          if (current.base_url) entry.base_url = current.base_url
          if (current.api_key) entry.api_key = current.api_key
          providers.push(entry)
        }
        current = {}
        // Parse the key on the same line as "- "
        const rest = trimmed.slice(2).trim()
        const kv = rest.match(/^(\w+):\s*(.+)$/)
        if (kv) {
          const key = kv[1] as keyof FallbackProvider
          const val = kv[2].trim().replace(/^["']|["']$/g, '')
          if (val) (current as Record<string, string>)[key] = val
        }
        continue
      }

      // Continuation line for current entry (indented, no "- ")
      if (current && trimmed) {
        const kv = trimmed.match(/^(\w+):\s*(.+)$/)
        if (kv) {
          const key = kv[1] as keyof FallbackProvider
          const val = kv[2].trim().replace(/^["']|["']$/g, '')
          if (val) (current as Record<string, string>)[key] = val
        }
      }
    }

    // Flush last entry
    if (current?.provider && current?.model) {
      const entry: FallbackProvider = { provider: current.provider, model: current.model }
      if (current.base_url) entry.base_url = current.base_url
      if (current.api_key) entry.api_key = current.api_key
      providers.push(entry)
    }

    return providers
  } catch {
    return []
  }
}

export function readModelProvider(dataDir: string): string {
  try {
    const configPath = path.join(dataDir, 'config.yaml')
    const content = fs.readFileSync(configPath, 'utf-8')
    const lines = content.split('\n')

    let inModelSection = false
    for (const line of lines) {
      const trimmed = line.trim()
      if (/^model:/.test(line)) { inModelSection = true; continue }
      if (/^\w/.test(line) && !trimmed.startsWith('#')) { inModelSection = false }
      if (inModelSection) {
        const provMatch = trimmed.match(/^provider:\s*(.+)$/)
        if (provMatch) return provMatch[1].trim().replace(/^["']|["']$/g, '')
      }
    }
    return ''
  } catch {
    return ''
  }
}

function readSoul(dataDir: string, maxChars = 200): string {
  try {
    const soulPath = path.join(dataDir, 'SOUL.md')
    const content = fs.readFileSync(soulPath, 'utf-8')
    // Strip markdown headers/lines, grab first meaningful text
    const lines = content
      .split('\n')
      .map((l) => l.trim())
      .filter((l) => l && !l.startsWith('#') && !l.startsWith('*') && !l.startsWith('---'))
    const text = lines.join(' ').slice(0, maxChars)
    return text || ''
  } catch {
    return ''
  }
}

function getComposeFilesForDir(hermesDir: string): string[] {
  const expanded = expandPath(hermesDir)
  try {
    const entries = fs.readdirSync(expanded)
    return entries
      .filter((f) => f.startsWith('docker-compose') && f.endsWith('.yml'))
      .map((f) => path.join(expanded, f))
  } catch {
    return []
  }
}

function getServicesFromComposeFile(composeFile: string): string[] {
  try {
    const output = execSync(
      `docker compose -f ${composeFile} config --services`,
      { stdio: 'pipe', timeout: 10000 }
    ).toString()
    return output.trim().split('\n').filter((s) => s.trim())
  } catch {
    return []
  }
}

// Map service name to the data directory where its SOUL.md lives
export function guessDataDir(serviceName: string, containerName: string): string {
  // hermes-personal → ~/.hermes (the default/personal instance)
  // hermes-osint → ~/.hermes-osint
  // seraph-thinker → ~/.hermes-seraph-thinker
  const home = os.homedir()
  if (containerName === 'hermes-personal' || serviceName === 'hermes-personal') {
    return path.join(home, '.hermes')
  }
  if (!serviceName) {
    return path.join(home, '.hermes-' + (containerName || 'unknown'))
  }
  if (serviceName.startsWith('hermes-')) {
    return path.join(home, '.' + serviceName)
  }
  // seraph-* agents
  if (serviceName.startsWith('seraph-')) {
    return path.join(home, '.hermes-' + serviceName)
  }
  return path.join(home, '.hermes-' + serviceName)
}

export class HarnessService {
  constructor(
    private storage: Storage,
    private docker: DockerService,
    private audit: AuditService,
    private config?: ConfigService,
  ) {}

  // Load stored overlays — tier, tools, keys, and other user-configured fields
  private loadOverlays(): Record<string, Partial<Harness>> {
    const stored = this.storage.read<Harness[]>(HARNESSES_FILE, [])
    const overlays: Record<string, Partial<Harness>> = {}
    for (const h of stored) {
      overlays[h.id] = h
    }
    return overlays
  }

  // Write overlays back — only persists user-configured fields, not live Docker state
  private saveOverlays(harnesses: Harness[]): void {
    this.storage.write(HARNESSES_FILE, harnesses)
  }

  discover(): { harnesses: Harness[]; error?: string } {
    if (!this.docker.isAvailable()) {
      return { harnesses: [], error: 'Docker is not available' }
    }

    const settings = this.config?.getSettings()
    const hermesDir = settings?.hermesDir ?? '~/Documents/GitHub/hermes-swarm'
    const configuredFiles = settings?.composeFiles ?? []

    // Determine which compose files to scan
    const composeFiles =
      configuredFiles.length > 0
        ? configuredFiles.map(expandPath)
        : getComposeFilesForDir(hermesDir)

    // Also scan standalone compose files created by Swarm Map
    const swarmMapDataDir = settings?.dataDir
      ? expandPath(settings.dataDir)
      : path.join(os.homedir(), '.hermes-swarm-map')
    const standaloneDir = path.join(swarmMapDataDir, 'compose')
    try {
      const dirs = fs.readdirSync(standaloneDir, { withFileTypes: true })
      for (const d of dirs) {
        if (!d.isDirectory()) continue
        const cf = path.join(standaloneDir, d.name, 'docker-compose.yml')
        if (fs.existsSync(cf) && !composeFiles.includes(cf)) {
          composeFiles.push(cf)
        }
      }
    } catch {}

    if (composeFiles.length === 0) {
      return { harnesses: [], error: `No docker-compose*.yml files found in ${hermesDir}` }
    }

    const overlays = this.loadOverlays()

    // Build a map of container name → live state via `docker compose ls` + per-project inspect
    // Use the project name "hermes-swarm" since that's how both files are deployed
    const liveContainers: Record<string, {
      state: string
      ports: Array<{ published: number; target: number }>
      composeFile: string
      serviceName: string
    }> = {}

    // Find the project names for our compose files via `docker compose ls`
    const projects = this.docker.listComposeProjects()
    // Build a set of absolute config file paths we care about
    const wantedFiles = new Set(composeFiles.map((f) => expandPath(f)))

    for (const project of projects) {
      const matchingFiles = project.configFiles.filter((f) => wantedFiles.has(f))
      if (matchingFiles.length === 0) continue

      const containers = this.docker.inspectContainers(project.name)
      for (const c of containers) {
        if (EXCLUDED_SERVICES.has(c.service)) continue
        // Prefer the config file that was in our wanted set
        const composeFile = c.composeFile ?? matchingFiles[0]
        liveContainers[c.name] = {
          state: c.state,
          ports: c.ports,
          composeFile,
          serviceName: c.service,
        }
      }
    }

    // If project-based lookup gave nothing, fall back to per-file inspection
    if (Object.keys(liveContainers).length === 0) {
      for (const composeFile of composeFiles) {
        const containers = this.docker.inspectContainers(
          path.basename(path.dirname(composeFile))
        )
        // Also try direct file-based approach
        const raw = this.docker.listContainers(composeFile)
        for (const c of raw) {
          if (EXCLUDED_SERVICES.has(c.service)) continue
          liveContainers[c.name] = {
            state: c.state,
            ports: [],
            composeFile,
            serviceName: c.service,
          }
        }
        void containers // suppress unused warning
      }
    }

    // Batch stats for ALL containers in one Docker call (~2s total, not 10s per container)
    const allStats = this.docker.getAllContainerStats()

    const harnesses: Harness[] = []

    for (const [containerName, live] of Object.entries(liveContainers)) {
      const name = containerNameToHarnessName(containerName)
      const id = 'h_' + name.replace(/-/g, '_')
      const dataDir = guessDataDir(live.serviceName, containerName)
      const persona = readSoul(dataDir)

      const stats = allStats[containerName] ?? { cpu: 0, memMiB: 0 }

      // Port: first published port
      const port = live.ports[0]?.published

      const overlay = overlays[id] ?? {}

      const harness: Harness = {
        // Discoverable fields
        id,
        name,
        runtime: 'hermes',
        status: stateToStatus(live.state),
        health: { errors: 0 },
        persona: persona || overlay.persona || `Hermes agent: ${name}`,
        lastSeen: Date.now(),
        cpu: stats.cpu,
        mem: stats.memMiB,
        composeFile: live.composeFile,
        serviceName: live.serviceName,
        // Overlay fields (user-configured) — fall back to sensible defaults
        tier: overlay.tier ?? 'individual',
        platform: overlay.platform ?? 'hermes',
        channel: overlay.channel ?? (port ? `:${port}` : ''),
        models: overlay.models?.length ? overlay.models : readModelConfig(dataDir),
        costToday: getCostToday(id),
        invocations: overlay.invocations ?? 0,
        tools: overlay.tools ?? [],
        ...(overlay.health ? { health: overlay.health } : {}),
        ...(overlay.cacheState ? { cacheState: overlay.cacheState } : {}),
        ...(overlay.cacheAge !== undefined ? { cacheAge: overlay.cacheAge } : {}),
        ...(overlay.parentId ? { parentId: overlay.parentId } : {}),
      }

      harnesses.push(harness)
    }

    // Sort: hermes-* first, then seraph-*
    harnesses.sort((a, b) => {
      const aIsSeraph = a.name.startsWith('seraph-') ? 1 : 0
      const bIsSeraph = b.name.startsWith('seraph-') ? 1 : 0
      if (aIsSeraph !== bIsSeraph) return aIsSeraph - bIsSeraph
      return a.name.localeCompare(b.name)
    })

    return { harnesses }
  }

  list(): Harness[] {
    const { harnesses } = this.discover()
    // Fall back to stored overlays if Docker discovery returned nothing
    if (harnesses.length === 0) {
      return this.storage.read<Harness[]>(HARNESSES_FILE, [])
    }
    return harnesses
  }

  get(id: string): Harness | undefined {
    return this.list().find((h) => h.id === id)
  }

  updateConfig(id: string, partial: Partial<Harness>): Harness | undefined {
    // Load existing overlays, merge, persist
    const overlays = this.storage.read<Harness[]>(HARNESSES_FILE, [])
    const index = overlays.findIndex((h) => h.id === id)
    if (index !== -1) {
      overlays[index] = { ...overlays[index], ...partial }
    } else {
      // New overlay entry — we need at least a skeleton
      const current = this.get(id)
      if (!current) return undefined
      overlays.push({ ...current, ...partial })
    }
    this.saveOverlays(overlays)
    return this.get(id)
  }

  restart(id: string, mode: RestartMode): void {
    const harness = this.get(id)
    if (!harness?.composeFile || !harness.serviceName) {
      throw new Error(`Harness ${id} has no compose file configured`)
    }
    this.docker.restart(harness.composeFile, harness.serviceName, mode)
    this.audit.append({ who: 'admin', what: `restart:${mode}`, target: harness.name })
  }

  start(id: string): void {
    const harness = this.get(id)
    if (!harness?.composeFile || !harness.serviceName) {
      throw new Error(`Harness ${id} has no compose file configured`)
    }
    this.docker.start(harness.composeFile, harness.serviceName)
    this.audit.append({ who: 'admin', what: 'start', target: harness.name })
  }

  stop(id: string): void {
    const harness = this.get(id)
    if (!harness?.composeFile || !harness.serviceName) {
      throw new Error(`Harness ${id} has no compose file configured`)
    }
    this.docker.stop(harness.composeFile, harness.serviceName)
    this.audit.append({ who: 'admin', what: 'stop', target: harness.name })
  }

  duplicateOverlay(sourceId: string, newName: string): Partial<Harness> | undefined {
    const overlays = this.storage.read<Partial<Harness>[]>('harnesses.json', [])
    const source = overlays.find((h) => h.id === sourceId)
    if (!source) return undefined

    const newId = 'h_' + newName.replace(/-/g, '_').replace(/\s+/g, '_')

    // Determine agent dirs
    const sourceName = source.name ?? sourceId.replace(/^h_/, '').replace(/_/g, '-')
    const sourceDataDir = path.join(os.homedir(), `.hermes-${sourceName}`)
    const newDataDir = path.join(os.homedir(), `.hermes-${newName}`)

    // Settings for compose dir
    const settings = this.config?.getSettings()
    const swarmMapDataDir = settings?.dataDir
      ? expandPath(settings.dataDir)
      : path.join(os.homedir(), '.hermes-swarm-map')
    const composeBaseDir = path.join(swarmMapDataDir, 'compose')

    // Pick next available port
    const port = nextAvailablePort(composeBaseDir)

    // Copy source data directory if it exists, else scaffold fresh
    if (fs.existsSync(sourceDataDir) && !fs.existsSync(newDataDir)) {
      // Deep copy using recursive dir copy
      copyDirRecursive(sourceDataDir, newDataDir)
      // Update port in the new .env
      const newEnvPath = path.join(newDataDir, '.env')
      if (fs.existsSync(newEnvPath)) {
        let envContent = fs.readFileSync(newEnvPath, 'utf-8')
        envContent = envContent.replace(
          /^API_SERVER_PORT=.*/m,
          `API_SERVER_PORT=${port}`
        )
        fs.writeFileSync(newEnvPath, envContent, { mode: 0o600 })
      }
    } else if (!fs.existsSync(newDataDir)) {
      scaffoldAgentDir(newDataDir, newName, port)
    }

    // Generate standalone compose for the duplicate
    const agentComposeDir = path.join(composeBaseDir, newName)
    fs.mkdirSync(agentComposeDir, { recursive: true })
    const composePath = path.join(agentComposeDir, 'docker-compose.yml')
    if (!fs.existsSync(composePath)) {
      fs.writeFileSync(composePath, generateStandaloneCompose(newName, port, newDataDir, resolveImageOrBuild(settings)), 'utf-8')
    }

    const duplicate: Partial<Harness> = {
      ...source,
      id: newId,
      name: newName,
      channel: `:${port}`,
      composeFile: composePath,
      serviceName: `hermes-${newName}`,
    }

    overlays.push(duplicate)
    this.storage.write('harnesses.json', overlays)

    this.audit.append({
      who: 'admin',
      what: 'duplicate',
      target: `${source.name ?? sourceId} → ${newName}`,
    })

    return duplicate
  }

  createOverlay(input: { name: string; tier?: HabitatTier; platform?: string; channel?: string; models?: string[]; tools?: string[] }): Partial<Harness> {
    const overlays = this.storage.read<Partial<Harness>[]>('harnesses.json', [])

    // Check for duplicate name
    const id = 'h_' + input.name.replace(/-/g, '_').replace(/\s+/g, '_')
    if (overlays.some((h) => h.id === id || h.name === input.name)) {
      throw new Error(`Harness "${input.name}" already exists`)
    }

    // Determine standalone compose directory from settings
    const settings = this.config?.getSettings()
    const swarmMapDataDir = settings?.dataDir
      ? expandPath(settings.dataDir)
      : path.join(os.homedir(), '.hermes-swarm-map')
    const composeBaseDir = path.join(swarmMapDataDir, 'compose')

    // Pick next available port
    const port = nextAvailablePort(composeBaseDir)

    // Agent data directory (where .env, config.yaml, SOUL.md live)
    const agentDir = path.join(os.homedir(), `.hermes-${input.name}`)

    // Scaffold agent data directory if it doesn't exist
    if (!fs.existsSync(agentDir)) {
      scaffoldAgentDir(agentDir, input.name, port)
    }

    // Generate standalone compose file
    const agentComposeDir = path.join(composeBaseDir, input.name)
    fs.mkdirSync(agentComposeDir, { recursive: true })
    const composePath = path.join(agentComposeDir, 'docker-compose.yml')
    if (!fs.existsSync(composePath)) {
      fs.writeFileSync(composePath, generateStandaloneCompose(input.name, port, agentDir, resolveImageOrBuild(settings)), 'utf-8')
    }

    const overlay: Partial<Harness> = {
      id,
      name: input.name,
      tier: input.tier ?? 'individual',
      platform: input.platform ?? 'hermes',
      channel: input.channel ?? `:${port}`,
      models: input.models ?? ['claude-sonnet-4-5'],
      tools: input.tools ?? [],
      composeFile: composePath,
      serviceName: `hermes-${input.name}`,
    }

    overlays.push(overlay)
    this.storage.write('harnesses.json', overlays)
    this.audit.append({ who: 'admin', what: 'create', target: input.name })
    return overlay
  }

  importFromDir(dataDir: string, name: string): Partial<Harness> {
    // Read SOUL.md for persona
    let persona = ''
    try {
      const soulPath = path.join(dataDir, 'SOUL.md')
      const content = fs.readFileSync(soulPath, 'utf-8')
      const lines = content
        .split('\n')
        .map((l) => l.trim())
        .filter((l) => l && !l.startsWith('#') && !l.startsWith('---'))
      persona = lines.join(' ').slice(0, 200)
    } catch {}

    // Parse .env for platform, port, and key detection
    const env = parseEnvFilePairs(path.join(dataDir, '.env'))
    let platform = 'hermes'
    if (env['MATTERMOST_TOKEN'] || env['MATTERMOST_URL']) {
      platform = 'mattermost'
    } else if (env['TELEGRAM_BOT_TOKEN']) {
      platform = 'telegram'
    }
    const port = env['API_SERVER_PORT'] ? parseInt(env['API_SERVER_PORT'], 10) : undefined
    const channel = port ? `:${port}` : ''

    // Read model config from config.yaml
    const models = readModelConfig(dataDir)

    // Read skills (subdirectory names under skills/)
    let tools: string[] = []
    try {
      const skillsDir = path.join(dataDir, 'skills')
      const entries = fs.readdirSync(skillsDir, { withFileTypes: true })
      tools = entries
        .filter((e) => e.isDirectory())
        .map((e) => e.name)
        .slice(0, 50)
    } catch {}

    // Try to find an existing compose file that references this agent
    let composeFile: string | undefined
    let serviceName: string | undefined
    const settings = this.config?.getSettings()
    const hermesDir = settings?.hermesDir ? expandPath(settings.hermesDir) : undefined
    if (hermesDir) {
      try {
        const composeFiles = getComposeFilesForDir(hermesDir)
        for (const cf of composeFiles) {
          try {
            const content = fs.readFileSync(cf, 'utf-8')
            // Look for the service name (hermes-{name} or just {name})
            const servicePatterns = [`hermes-${name}`, name]
            for (const svc of servicePatterns) {
              if (content.includes(`${svc}:`)) {
                composeFile = cf
                serviceName = svc
                break
              }
            }
          } catch {}
          if (composeFile) break
        }
      } catch {}
    }

    // Also check the standalone compose location
    if (!composeFile) {
      const swarmMapDataDir = settings?.dataDir
        ? expandPath(settings.dataDir)
        : path.join(os.homedir(), '.hermes-swarm-map')
      const standalonePath = path.join(swarmMapDataDir, 'compose', name, 'docker-compose.yml')
      if (fs.existsSync(standalonePath)) {
        composeFile = standalonePath
        serviceName = `hermes-${name}`
      }
    }

    const overlay = this.createOverlay({ name, platform, channel, models })

    // Patch with richer fields not available in createOverlay input
    const patches: Partial<Harness> = {}
    if (persona) patches.persona = persona
    if (tools.length > 0) patches.tools = tools
    if (composeFile) patches.composeFile = composeFile
    if (serviceName) patches.serviceName = serviceName

    if (Object.keys(patches).length > 0) {
      Object.assign(overlay, patches)
      const overlays = this.storage.read<Partial<Harness>[]>('harnesses.json', [])
      const idx = overlays.findIndex((h) => h.id === overlay.id)
      if (idx !== -1) {
        overlays[idx] = { ...overlays[idx], ...patches }
        this.storage.write('harnesses.json', overlays)
      }
    }

    return overlay
  }

  restartRunning(): { restarted: string[]; errors: Record<string, string> } {
    const running = this.list().filter((h) => h.status === 'running')
    const restarted: string[] = []
    const errors: Record<string, string> = {}
    for (const harness of running) {
      try {
        if (harness.composeFile && harness.serviceName) {
          this.docker.restart(harness.composeFile, harness.serviceName, 'quick')
          restarted.push(harness.id)
          this.audit.append({ who: 'admin', what: 'restart:quick', target: harness.name })
        }
      } catch (err) {
        errors[harness.id] = err instanceof Error ? err.message : String(err)
      }
    }
    return { restarted, errors }
  }
}
