import { describe, it, expect } from 'vitest'
import {
  generateStandaloneCompose,
  renderExtraEnv,
  renderExtraMounts,
} from './harness-compose'
import type { ExtraMount } from '@/lib/types'

/**
 * The lines of a service's block-scalar list, e.g. `volumes:` or
 * `environment:`, without parsing YAML (the project has no yaml dependency and
 * this is not worth adding one for). Walks from the key to the first line that
 * dedents out of the list, so an entry emitted at the wrong indent — which
 * would land in the wrong block or break the file — fails the assertion.
 */
function listEntries(compose: string, service: string, key: string): string[] {
  const lines = compose.split('\n')
  const serviceIdx = lines.findIndex((l) => l === `  ${service}:`)
  if (serviceIdx < 0) throw new Error(`no service ${service}`)
  let keyIdx = -1
  for (let i = serviceIdx + 1; i < lines.length; i++) {
    if (/^ {2}\S/.test(lines[i])) break // next service
    if (lines[i] === `    ${key}:`) { keyIdx = i; break }
  }
  if (keyIdx < 0) throw new Error(`no ${key}: in ${service}`)
  const out: string[] = []
  for (let i = keyIdx + 1; i < lines.length; i++) {
    const line = lines[i]
    if (/^ {6}#/.test(line)) continue // comment inside the list
    if (!/^ {6}- /.test(line)) break
    out.push(line.slice(8))
  }
  return out
}

// The bug these exist for: an agent needed a host path, someone added the
// mount by hand under the "# Generated by hermes-swarm-map" header, and the
// next regeneration silently dropped it. The container came back healthy with
// the capability gone. So: mounts are config, config survives regeneration,
// and a malformed mount fails generation loudly instead of rendering into
// something that means more than it says.

const agentName = 'test-agent'
const port = 8642
const dataDir = '/opt/hermes/test-agent'

const SPOOL: ExtraMount = {
  hostPath: '/Users/juni/.iris/nimbleco/intake',
  containerPath: '/opt/iris-intake',
  mode: 'rw',
  note: 'approval-gate spool: the only writable gate path',
}
const PACKAGE: ExtraMount = {
  hostPath: '/Users/juni/iris-gates/nimbleco',
  containerPath: '/opt/iris',
}

describe('renderExtraMounts', () => {
  it('renders nothing when there are no mounts', () => {
    expect(renderExtraMounts()).toBe('')
    expect(renderExtraMounts([])).toBe('')
  })

  it('defaults mode to ro — write access has to be asked for', () => {
    expect(renderExtraMounts([PACKAGE])).toBe(
      '      - /Users/juni/iris-gates/nimbleco:/opt/iris:ro\n')
  })

  it('renders the note as a comment above the mount', () => {
    const out = renderExtraMounts([SPOOL])
    expect(out).toContain('# approval-gate spool: the only writable gate path')
    expect(out).toContain('- /Users/juni/.iris/nimbleco/intake:/opt/iris-intake:rw')
  })

  // --- injection: every value lands in generated YAML -----------------------

  it('refuses a newline in a path — it could append arbitrary compose keys', () => {
    for (const evil of [
      { hostPath: '/a\n    privileged: true', containerPath: '/b' },
      { hostPath: '/a', containerPath: '/b\n      - /etc:/etc:rw' },
    ] as ExtraMount[]) {
      expect(() => renderExtraMounts([evil])).toThrow(/newline/)
    }
  })

  it('refuses a colon in a path — it could forge the mount mode', () => {
    // '/host:/container:rw' smuggled through what looks like one path would
    // turn a declared-ro mount into a writable one.
    expect(() => renderExtraMounts([
      { hostPath: '/etc:/etc:rw', containerPath: '/b', mode: 'ro' },
    ])).toThrow(/forge the mount mode/)
  })

  it('refuses a relative path', () => {
    expect(() => renderExtraMounts([
      { hostPath: 'relative/path', containerPath: '/b' },
    ])).toThrow(/absolute/)
  })

  it('refuses an empty path', () => {
    expect(() => renderExtraMounts([
      { hostPath: '', containerPath: '/b' },
    ])).toThrow(/required/)
  })

  it('refuses a mode that is not ro or rw', () => {
    expect(() => renderExtraMounts([
      { hostPath: '/a', containerPath: '/b', mode: 'z' as 'ro' },
    ])).toThrow(/must be 'ro' or 'rw'/)
  })

  it('names the offending index so a bad entry is findable', () => {
    expect(() => renderExtraMounts([PACKAGE, { hostPath: 'nope', containerPath: '/b' }]))
      .toThrow(/extraMounts\[1\]/)
  })
})

describe('renderExtraEnv', () => {
  it('renders nothing when absent', () => {
    expect(renderExtraEnv()).toBe('')
  })

  it('renders KEY=value list entries', () => {
    expect(renderExtraEnv({ IRIS_BRAND: 'nimbleco' }))
      .toBe('      - IRIS_BRAND=nimbleco\n')
  })

  it('refuses a newline in a key or value', () => {
    expect(() => renderExtraEnv({ A: 'x\n      - B=y' })).toThrow(/newline/)
  })

  it('refuses a key that is not a valid env var name', () => {
    expect(() => renderExtraEnv({ 'not a key': 'x' })).toThrow(/valid environment variable name/)
  })
})

describe('generateStandaloneCompose with extra mounts', () => {
  for (const [label, vpnEnabled] of [['plain', false], ['VPN', true]] as const) {
    describe(label, () => {
      it('emits the mounts and env into the hermes service blocks', () => {
        const compose = generateStandaloneCompose(agentName, port, dataDir, {
          vpnEnabled,
          extraMounts: [SPOOL, PACKAGE],
          extraEnv: { IRIS_INTAKE_DIR: '/opt/iris-intake', IRIS_BRAND: 'nimbleco' },
        })
        const volumes = listEntries(compose, `hermes-${agentName}`, 'volumes')
        const environment = listEntries(compose, `hermes-${agentName}`, 'environment')

        expect(volumes).toContain('/Users/juni/.iris/nimbleco/intake:/opt/iris-intake:rw')
        expect(volumes).toContain('/Users/juni/iris-gates/nimbleco:/opt/iris:ro')
        // The standard mounts survive alongside them.
        expect(volumes).toContain(`${dataDir}:/opt/data`)
        expect(environment).toContain('IRIS_INTAKE_DIR=/opt/iris-intake')
        expect(environment).toContain('IRIS_BRAND=nimbleco')
        expect(environment).toContain('HERMES_HOME=/opt/data')
        // command: must still follow the volumes block, not be swallowed by it.
        expect(compose).toContain('    command: gateway')
      })

      it('is byte-identical to the old output when no extras are configured', () => {
        // The regression guard for every existing agent: adding this feature
        // must not perturb a compose file that does not use it.
        const without = generateStandaloneCompose(agentName, port, dataDir, { vpnEnabled })
        const withEmpty = generateStandaloneCompose(agentName, port, dataDir, {
          vpnEnabled, extraMounts: [], extraEnv: {},
        })
        expect(withEmpty).toBe(without)
      })

      it('fails generation rather than emitting a malformed mount', () => {
        expect(() => generateStandaloneCompose(agentName, port, dataDir, {
          vpnEnabled,
          extraMounts: [{ hostPath: '/a\n    privileged: true', containerPath: '/b' }],
        })).toThrow(/newline/)
      })
    })
  }

  it('survives regeneration — the whole point', () => {
    const options = {
      extraMounts: [SPOOL, PACKAGE],
      extraEnv: { IRIS_INTAKE_DIR: '/opt/iris-intake' },
    }
    const first = generateStandaloneCompose(agentName, port, dataDir, options)
    const regenerated = generateStandaloneCompose(agentName, port, dataDir, options)
    expect(regenerated).toBe(first)
    expect(regenerated).toContain('/opt/iris-intake:rw')
  })
})
