/**
 * Opinionated config.yaml template for new Hermes agents.
 * Shared across all agent creation paths (overlay + full deploy).
 */

export function generateDefaultConfig(params: {
  provider: string
  primaryModel: string
  fallbackModel?: string
  browserEnabled?: boolean
}): string {
  const { provider, primaryModel, fallbackModel, browserEnabled } = params

  const fallbackLine = fallbackModel
    ? `  fallback: ${fallbackModel}`
    : `  # fallback: <model>  # uncomment to set a fallback model`

  return `# Hermes Agent — generated by Swarm Map
# Full reference: https://github.com/NousResearch/hermes-agent/blob/main/cli-config.yaml.example

model:
  provider: ${provider === 'ollama' ? 'custom' : provider}
  default: ${primaryModel}
${provider === 'ollama' || provider === 'custom' ? '  base_url: "http://host.docker.internal:11434/v1"\n' : ''}${fallbackLine}

# --- Context compression (prevents OOM on long conversations) ---
compression:
  enabled: true
  threshold: 0.50
  target_ratio: 0.20
  protect_last_n: 20
  summary_model: "google/gemini-3-flash-preview"

# --- Persistent memory (carries knowledge across sessions) ---
memory:
  memory_enabled: true
  user_profile_enabled: true
  memory_char_limit: 2200
  user_char_limit: 1375
  nudge_interval: 10
  flush_min_turns: 6

# --- Session reset (messaging platforms — prevents runaway token costs) ---
session_reset:
  mode: both
  idle_minutes: 1440
  at_hour: 4

group_sessions_per_user: true

# --- Agent behavior ---
agent:
  max_turns: 60
  verbose: false
  reasoning_effort: "medium"

# --- Voice transcription (pre-installed in Docker) ---
stt:
  enabled: true
  local:
    model: "base"

# --- Text-to-Speech (Edge TTS — free, no API key) ---
tts:
  enabled: true
  default_provider: "edge"
  edge:
    voice: "en-US-AriaNeural"

# --- Terminal access ---
terminal:
  backend: "local"
  cwd: "."
  timeout: 180
${browserEnabled ? `
# --- Browser ---
browser:
  inactivity_timeout: 120
  command_timeout: 30
  camofox:
    managed_persistence: false
` : ''}

# --- Skills ---
skills:
  creation_nudge_interval: 15

# --- Display ---
display:
  compact: false
  tool_progress: all
  interim_assistant_messages: true
  streaming: true

# --- Platform toolsets (explicit defaults) ---
platform_toolsets:
  cli: [hermes-cli]
  telegram: [hermes-telegram]
  discord: [hermes-discord]
  signal: [hermes-signal]
  slack: [hermes-slack]
  mattermost: [hermes-mattermost]
`
}
